use super::*;
use super::{codex_watch::WatchSnapshot,watch_reply::WatchReply};
#[test]fn cumulative_usage_survives_restart_deduplicates_and_excludes_other_origins(){
 let d=tempfile::tempdir().unwrap();let path=d.path().join("router.db");let s=RouterStore::open_at(&path).unwrap();let snap=WatchSnapshot{state:"IDLE".into(),turn_id:None,item_id:None,text:String::new()};for id in ["low-usage","high-usage"]{s.enable_codex_watch(id,id,d.path().to_str().unwrap(),&snap).unwrap();}
 let request=|thread:&str,mode:&str|WatchReply{id:id(),thread_id:thread.into(),cwd:d.path().to_string_lossy().into_owned(),generation:1,source_sequence:None,expected_turn_id:None,mode:mode.into(),text:"fictional reply".into(),options:serde_json::json!({}),payload_hash:String::new(),status:String::new(),turn_id:None,error_code:None,created_at:0,updated_at:0};
 for thread in ["low-usage","high-usage","high-usage"]{let r=request(thread,"SEND");s.prepare_watch_reply(&r).unwrap();s.claim_watch_reply(&r.id).unwrap();s.finish_watch_reply(&r.id,"SENT",Some("turn"),None).unwrap();assert_eq!(s.prepare_watch_reply(&r).unwrap().status,"SENT");}
 let failed=request("low-usage","SEND");s.prepare_watch_reply(&failed).unwrap();s.finish_watch_reply(&failed.id,"FAILED",None,Some("PREWRITE" )).unwrap();
 let queue=request("high-usage","QUEUE");s.prepare_watch_reply(&queue).unwrap();s.cancel_watch_reply("high-usage",&queue.id).unwrap();
 let event=WatchSnapshot{state:"RESULT_READY".into(),turn_id:Some("event-turn".into()),item_id:Some("event-item".into()),text:"event result".into()};s.record_codex_watch("low-usage",1,&event).unwrap();let seq=s.codex_watch_feed(0).unwrap().events[0].sequence;let mut event_reply=request("low-usage","SEND");event_reply.source_sequence=Some(seq);s.prepare_watch_reply(&event_reply).unwrap();s.claim_watch_reply(&event_reply.id).unwrap();s.finish_watch_reply(&event_reply.id,"SENT",Some("turn"),None).unwrap();
 let assistant=request("low-usage","SEND");s.prepare_watch_reply(&assistant).unwrap();s.claim_watch_reply(&assistant.id).unwrap();s.finish_watch_reply(&assistant.id,"SENT",Some("turn"),None).unwrap();s.with_connection(|c|{c.execute("INSERT INTO assistant_grants(id,workstream_id,source_role,binding_revision,label,brief_json,created_at,expires_at,scope) VALUES('fixture-grant',NULL,'BOTH',0,'fixture','{}',1,9999999999999,'INSTANCE')",[]).map_err(db_error)?;c.execute("INSERT INTO assistant_actions(id,grant_id,request_id,payload_hash,operation,input_json,status,created_at,updated_at) VALUES(?1,'fixture-grant','request','hash','SEND_CHAT','{}','APPLIED',1,1)",[&assistant.id]).map_err(db_error)?;Ok(())}).unwrap();
 let rows=s.codex_watches().unwrap();assert_eq!(rows[0].thread_id,"high-usage");assert_eq!(rows[0].send_count,3);assert_eq!(rows[1].send_count,1);s.pause_codex_watch("high-usage").unwrap();drop(s);let s=RouterStore::open_at(path).unwrap();assert_eq!(s.codex_watches().unwrap()[0].send_count,3);
}
