import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const src=fs.readFileSync(new URL('./worker.mjs',import.meta.url),'utf8').replace("import {DurableObject} from 'cloudflare:workers';","class DurableObject {constructor(){}}");
const {default:worker,Control,Tenant,hash}=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
class Storage{data=new Map();async get(k){return structuredClone(this.data.get(k));}async put(k,v){if(typeof k==='string')this.data.set(k,structuredClone(v));else for(const [key,val] of Object.entries(k))this.data.set(key,structuredClone(val));}async list({prefix}){return new Map([...this.data].filter(([k])=>k.startsWith(prefix)));}async setAlarm(t){this.alarm=t;}}
function context(){const storage=new Storage();let q=Promise.resolve();return {storage,sockets:[],getWebSockets(){return this.sockets;},blockConcurrencyWhile(fn){const n=q.then(fn);q=n.catch(()=>{});return n;}};}
function fixture(){const env={ADMIN_TOKEN:'a'.repeat(64),CONTROL_HOST:'connect.example.invalid',ZONE_ROOT:'example.invalid'},c=context(),tenants=new Map();env.TENANTS={idFromName:n=>n,get:n=>{if(!tenants.has(n))tenants.set(n,new Tenant(context(),env));return tenants.get(n);}};const control=new Control(c,env);env.CONTROL={idFromName:n=>n,get:()=>control};return {env,c,tenants,call:async(path,body,admin=false)=>worker.fetch(new Request('https://'+env.CONTROL_HOST+path,{method:'POST',headers:{'content-type':'application/json',...(admin?{Authorization:'Bearer '+env.ADMIN_TOKEN}:{})},body:JSON.stringify(body)}),env)};}
async function issue(f,days=7,id=crypto.randomUUID().replaceAll('-','')){const code=`AGB${days}-`+'b'.repeat(64),h=await hash(code);assert.equal((await f.call('/admin/issue',{codes:[{hash:h,tenantId:id,days}]},true)).status,200);assert.equal((await f.call('/admin/ready',{hashes:[h]},true)).status,200);return {code,hash:h,id};}
test('admin is separate; unprepared code cannot activate',async()=>{const f=fixture();assert.equal((await f.call('/admin/issue',{codes:[]})).status,401);const code='AGB7-'+'b'.repeat(64);await f.call('/admin/issue',{codes:[{hash:await hash(code),tenantId:'a'.repeat(32),days:7}]},true);assert.equal((await f.call('/v1/redeem',{code,deviceKey:'c'.repeat(64)})).status,503);});
test('concurrent redemption binds once and retries do not extend expiry',async()=>{const f=fixture(),c=await issue(f);const responses=await Promise.all([f.call('/v1/redeem',{code:c.code,deviceKey:'c'.repeat(64)}),f.call('/v1/redeem',{code:c.code,deviceKey:'d'.repeat(64)})]);assert.deepEqual(responses.map(r=>r.status),[200,409]);const a=await responses[0].json(),b=await(await f.call('/v1/redeem',{code:c.code,deviceKey:'c'.repeat(64)})).json();assert.deepEqual(a,b);assert.ok(a.expiresAt-Date.now()>6.99*86400000);assert.equal(a.tenantId,c.id);assert.equal((await f.c.storage.get('c:'+c.hash)).code,undefined);});
test('distinct devices get distinct origins and connector capabilities; renewal retains tenant',async()=>{const f=fixture(),c=await issue(f),a=await(await f.call('/v1/redeem',{code:c.code,deviceKey:'c'.repeat(64)})).json();const code2='AGB30-'+'d'.repeat(64),h=await hash(code2),id='e'.repeat(32);await f.call('/admin/issue',{codes:[{hash:h,tenantId:id,days:30}]},true);await f.call('/admin/ready',{hashes:[h]},true);const b=await(await f.call('/v1/redeem',{code:code2,deviceKey:'f'.repeat(64)})).json();assert.notEqual(a.origin,b.origin);assert.notEqual(a.hostToken,b.hostToken);const code3='AGB365-'+'e'.repeat(64),h3=await hash(code3);await f.call('/admin/issue',{codes:[{hash:h3,tenantId:'f'.repeat(32),days:365}]},true);await f.call('/admin/ready',{hashes:[h3]},true);const renewal=await(await f.call('/v1/redeem',{code:code3,deviceKey:'c'.repeat(64)})).json();assert.equal(renewal.tenantId,a.tenantId);assert.equal(renewal.hostToken,a.hostToken);assert.equal(renewal.expiresAt,a.expiresAt+365*86400000);});
test('revocation/expiry enforced on live public request and old code cannot revive',async()=>{const f=fixture(),c=await issue(f),a=await(await f.call('/v1/redeem',{code:c.code,deviceKey:'c'.repeat(64)})).json(),t=f.tenants.get(a.tenantId);assert.equal((await t.fetch(new Request(a.origin+'/mobile'))).status,503);const prior=Date.now;try{Date.now=()=>a.expiresAt+1;assert.equal((await t.fetch(new Request(a.origin+'/mobile'))).status,402);}finally{Date.now=prior;}await f.call('/admin/revoke',{hash:c.hash},true);assert.equal((await t.fetch(new Request(a.origin+'/mobile'))).status,402);assert.equal((await f.call('/v1/redeem',{code:c.code,deviceKey:'c'.repeat(64)})).status,403);});
test('tenant host, origin, socket token and request frames never cross',async()=>{const f=fixture(),c=await issue(f),a=await(await f.call('/v1/redeem',{code:c.code,deviceKey:'c'.repeat(64)})).json(),t=f.tenants.get(a.tenantId);assert.equal((await t.fetch(new Request('https://ag-'+ 'd'.repeat(32)+'.example.invalid/mobile'))).status,404);const sock={attachment:{authorized:false},deserializeAttachment(){return this.attachment;},serializeAttachment(a){this.attachment=a;},close(){this.closed=true;},send(m){this.sent=m;}};t.ctx.sockets.push(sock);await t.webSocketMessage(sock,JSON.stringify({type:'auth',token:'f'.repeat(64)}));assert.ok(sock.closed);sock.closed=false;await t.webSocketMessage(sock,JSON.stringify({type:'auth',token:a.hostToken}));assert.ok(sock.attachment.authorized);assert.equal((await t.fetch(new Request(a.origin+'/mobile',{headers:{Origin:'https://other.example.invalid'}}))).status,403);sock.send=m=>{const frame=JSON.parse(m);assert.equal(frame.path,'/mobile');assert.equal(frame.headers.some(([k])=>k==='cf-access-jwt-assertion'),false);queueMicrotask(()=>t.webSocketMessage(sock,JSON.stringify({type:'response',id:frame.id,status:200,headers:[['content-type','text/plain']],body:Buffer.from('tenant-a-only').toString('base64')})));};const r=await t.fetch(new Request(a.origin+'/mobile',{headers:{'cf-access-jwt-assertion':'never-forward'}}));assert.equal(await r.text(),'tenant-a-only');});
test('control and tenant routes deny unapproved hosts/methods/Origins',async()=>{const f=fixture();assert.equal((await worker.fetch(new Request('https://else.example.invalid/health'),f.env)).status,404);assert.equal((await worker.fetch(new Request('http://connect.example.invalid/health'),f.env)).status,400);assert.equal((await worker.fetch(new Request('https://connect.example.invalid/v1/redeem',{method:'POST',headers:{Origin:'https://attacker.invalid'},body:'{}'}),f.env)).status,403);});
test('replaying an older code after renewal neither shortens nor reactivates service',async()=>{const f=fixture(),c=await issue(f),key='c'.repeat(64);const original=await(await f.call('/v1/redeem',{code:c.code,deviceKey:key})).json();const code='AGB30-'+'e'.repeat(64),h=await hash(code);await f.call('/admin/issue',{codes:[{hash:h,tenantId:'f'.repeat(32),days:30}]},true);await f.call('/admin/ready',{hashes:[h]},true);const renewed=await(await f.call('/v1/redeem',{code,deviceKey:key})).json();assert.equal(renewed.expiresAt,original.expiresAt+30*86400000);const retry=await(await f.call('/v1/redeem',{code:c.code,deviceKey:key})).json();assert.equal(retry.expiresAt,renewed.expiresAt);await f.call('/admin/expire',{hash:c.hash},true);const old=await(await f.call('/v1/redeem',{code:c.code,deviceKey:key})).json();assert.ok(old.expiresAt<Date.now());assert.equal((await f.tenants.get(old.tenantId).fetch(new Request(old.origin+'/mobile'))).status,402);});
