import { useCallback, useEffect, useState } from "react";
import { mobileApi, type ChatHistory, type CodexHistory, type MobileAttachment, type MobileCodexRequest, type MobileFeedbackProgress, type MobileReplyObservation, type MobileReview, type MobileReviewResult, type MobileWorkstream } from "./api";
import { ChatGptReplyObservations, CodexRequests, HandoffReview, HistoryPanels, ReviewResults, WorkstreamList } from "./WorkbenchSections";
import { disableWebPush, enableWebPush, pushSetupState, type PushSetupState } from "./push";

function errorMessage(cause: unknown) {
  if (cause instanceof Error && cause.message.trim()) return cause.message;
  const fallback = String(cause).trim();
  return fallback && fallback !== "Error" ? fallback : "Unknown request error";
}

export function MobileWorkbench() {
  const [workstreams, setWorkstreams] = useState<MobileWorkstream[]>([]); const [selected, setSelected] = useState<MobileWorkstream>(); const [results, setResults] = useState<MobileReviewResult[]>([]); const [observations, setObservations] = useState<MobileReplyObservation[]>([]); const [requests, setRequests] = useState<MobileCodexRequest[]>([]); const [chat, setChat] = useState<ChatHistory>(); const [codex, setCodex] = useState<CodexHistory>(); const [review, setReview] = useState<MobileReview>(); const [reviewDirection, setReviewDirection] = useState<"CHATGPT_TO_CODEX" | "CODEX_TO_CHATGPT">("CHATGPT_TO_CODEX"); const [message, setMessage] = useState(""); const [preparedAttachments, setPreparedAttachments] = useState<MobileAttachment[]>([]); const [feedbacks, setFeedbacks] = useState<Record<string, string>>({}); const [feedbackSendingRunId, setFeedbackSendingRunId] = useState<string>(); const [feedbackWaitingRunId, setFeedbackWaitingRunId] = useState<string>(); const [feedbackProgress, setFeedbackProgress] = useState<{ sourceRunId: string; progress: MobileFeedbackProgress }>(); const [feedbackRecoveryNotice, setFeedbackRecoveryNotice] = useState<{ sourceRunId: string; message: string }>(); const [requestSendingId, setRequestSendingId] = useState<string>(); const [error, setError] = useState(""); const [pushNotice, setPushNotice] = useState<PushSetupState>("NOT_REQUESTED"); const [historyNotice, setHistoryNotice] = useState(""); const [historyLoading, setHistoryLoading] = useState(false); const [historyLoaded, setHistoryLoaded] = useState(false);
  const refresh = useCallback(async () => { try { setWorkstreams(await mobileApi.workstreams()); setError(""); } catch (cause) { setError(`Unable to load Workstreams: ${errorMessage(cause)}`); } }, []);
  useEffect(() => { void refresh(); const id = window.setInterval(() => void refresh(), 15_000); return () => clearInterval(id); }, [refresh]);
  useEffect(() => { void pushSetupState().then(setPushNotice, () => setPushNotice("UNSUPPORTED")); }, []);
  const loadSemanticState = useCallback(async (item: MobileWorkstream) => { const [nextResults, nextObservations, nextRequests] = await Promise.allSettled([mobileApi.reviewResults(item.id), mobileApi.replyObservations(item.id), mobileApi.codexRequests(item.id)]); if (nextResults.status === "fulfilled") setResults(nextResults.value); else setError(`Unable to load reviewable provider results: ${errorMessage(nextResults.reason)}`); if (nextObservations.status === "fulfilled") setObservations(nextObservations.value); if (nextRequests.status === "fulfilled") setRequests(nextRequests.value); else setError(`Unable to load Codex requests: ${errorMessage(nextRequests.reason)}`); }, []);
  const open = async (item: MobileWorkstream) => { setSelected(item); setReview(undefined); setPreparedAttachments([]); setChat(undefined); setCodex(undefined); setResults([]); setObservations([]); setRequests([]); setFeedbacks({}); setFeedbackWaitingRunId(undefined); setFeedbackProgress(undefined); setFeedbackRecoveryNotice(undefined); setHistoryNotice(""); setHistoryLoaded(false); setError(""); await loadSemanticState(item); };
  const refreshSelected = async () => { if (selected) { setError(""); try { const recovery = await mobileApi.recoverChatGptResult(selected.id); if (recovery.recovered) setHistoryNotice(recovery.message); await loadSemanticState(selected); } catch (cause) { setError(`Unable to refresh the exact ChatGPT result: ${errorMessage(cause)}`); await loadSemanticState(selected); } } };
  const recoverFeedbackResult = async (runId: string) => { if (!selected) return; setError(""); setFeedbackRecoveryNotice(undefined); try { const recovery = await mobileApi.recoverChatGptFeedbackResult(selected.id, runId); if (recovery.recovered) { await loadSemanticState(selected); setFeedbackProgress(undefined); setFeedbackWaitingRunId(undefined); } else { setFeedbackRecoveryNotice({ sourceRunId: feedbackProgress?.sourceRunId ?? runId, message: recovery.message }); setFeedbackProgress({ sourceRunId: feedbackProgress?.sourceRunId ?? runId, progress: await mobileApi.chatgptFeedbackProgress(selected.id, runId) }); } } catch { setFeedbackRecoveryNotice({ sourceRunId: feedbackProgress?.sourceRunId ?? runId, message: "这条完整结果暂时无法重新读取：Router 尚未确认同一条助手回复的精确身份。未发送任何消息，也不会自动重试。" }); } };
  const refreshHandoff = async () => { await refreshSelected(); if (reviewDirection !== "CODEX_TO_CHATGPT" || !review) return; try { setReview(await mobileApi.codexHandoffReview(review.actionId)); } catch (cause) { setError(`Unable to refresh Handoff delivery state: ${errorMessage(cause)}`); } };
  const loadHistory = async () => { if (!selected || historyLoading || historyLoaded) return; setHistoryLoading(true); const [nextChat, nextCodex] = await Promise.allSettled([mobileApi.chatgptHistory(selected.id), mobileApi.codexHistory(selected.id)]); if (nextChat.status === "fulfilled") setChat(nextChat.value); if (nextCodex.status === "fulfilled") setCodex(nextCodex.value); const unavailable = [nextChat.status === "rejected" ? `ChatGPT history: ${errorMessage(nextChat.reason)}` : "", nextCodex.status === "rejected" ? `Codex history: ${errorMessage(nextCodex.reason)}` : ""].filter(Boolean); setHistoryNotice(unavailable.length ? `Read-only detail unavailable. ${unavailable.join(" · ")}` : ""); setHistoryLoaded(true); setHistoryLoading(false); };
  const prepare = async (result: MobileReviewResult) => { if (!selected || result.provider !== "CHATGPT" || !result.markerText?.trim()) return; try { const next = await mobileApi.prepareHandoff(selected.id, result.resultIdentity); setReview(next); setReviewDirection("CHATGPT_TO_CODEX"); setMessage(next.message); setError(""); } catch (cause) { setError(`Unable to prepare Handoff: ${errorMessage(cause)}`); } };
  const prepareObservation = async (observation: MobileReplyObservation) => { if (!selected || !observation.markerText?.trim()) return; try { const next = await mobileApi.prepareHandoff(selected.id, observation.id); await mobileApi.markReplyObservationHandled(selected.id, observation.id); setObservations(current => current.map(item => item.id === observation.id ? { ...item, handledAt: Date.now() } : item)); setReview(next); setReviewDirection("CHATGPT_TO_CODEX"); setMessage(next.message); setError(""); } catch (cause) { setError(`Unable to prepare observed reply Handoff: ${errorMessage(cause)}`); } };
  const markObservationRead = async (observation: MobileReplyObservation, handled = false) => { if (!selected) return; try { if (handled) await mobileApi.markReplyObservationHandled(selected.id, observation.id); else await mobileApi.markReplyObservationRead(selected.id, observation.id); setObservations(current => current.map(item => item.id === observation.id ? { ...item, readAt: item.readAt ?? Date.now(), handledAt: handled ? Date.now() : item.handledAt } : item)); } catch (cause) { setError(`Unable to update reply state: ${errorMessage(cause)}`); } };
  const prepareCodex = async (result: MobileReviewResult, draft: string, attachmentIds: string[], attachments: MobileAttachment[]) => { if (!selected || result.provider !== "CODEX" || !draft.trim()) return; try { const next = await mobileApi.prepareCodexHandoff(selected.id, result.runId, attachmentIds); setReview(next); setReviewDirection("CODEX_TO_CHATGPT"); setMessage(draft.trim()); setPreparedAttachments(attachments); setError(""); } catch (cause) { setError(`Unable to prepare Codex Handoff: ${errorMessage(cause)}`); } };
  const approve = async () => { if (!review) return; try { const next = reviewDirection === "CHATGPT_TO_CODEX" ? await mobileApi.approveHandoff(review.actionId, review.revision, message) : await mobileApi.approveCodexHandoff(review.actionId, review.revision, message); setReview(next); setError(""); } catch (cause) { setError(`Unable to approve Handoff: ${errorMessage(cause)}`); } };
  const send = async () => { if (!review) return; try { if (reviewDirection === "CHATGPT_TO_CODEX") { await mobileApi.sendHandoff(review.actionId, review.revision); setReview({ ...review, status: "SENT" }); } else { const delivery = await mobileApi.sendCodexHandoff(review.actionId, review.revision); setReview({ ...review, status: delivery.status }); } setError(""); } catch (cause) { setError(`Unable to send Handoff: ${errorMessage(cause)}`); } };
  const sendFeedback = async (result: MobileReviewResult) => { if (!selected) return; const feedback = feedbacks[result.runId]?.trim(); if (!feedback) return; setFeedbackSendingRunId(result.runId); try { if (result.provider === "CHATGPT") { const progress = await mobileApi.sendChatGptFeedback(selected.id, result.runId, feedback); setFeedbackProgress({ sourceRunId: result.runId, progress }); } else await mobileApi.sendCodexFeedback(selected.id, result.runId, feedback); setFeedbacks(current => ({ ...current, [result.runId]: "" })); setFeedbackWaitingRunId(result.runId); setError(""); } catch (cause) { setError(`Unable to send ${result.provider === "CHATGPT" ? "ChatGPT" : "Codex"} feedback: ${errorMessage(cause)}`); } finally { setFeedbackSendingRunId(undefined); } };
  useEffect(() => { if (!selected || !feedbackProgress || feedbackProgress.progress.phase !== "WAITING_FOR_REVISED_RESULT") return; let cancelled = false; const poll = async () => { try { const progress = await mobileApi.chatgptFeedbackProgress(selected.id, feedbackProgress.progress.runId); if (cancelled) return; setFeedbackProgress(current => current?.progress.runId === progress.runId ? { ...current, progress } : current); if (progress.phase === "REVISED_RESULT_READY") await loadSemanticState(selected); } catch (cause) { if (!cancelled) setError(`Unable to confirm ChatGPT feedback delivery: ${errorMessage(cause)}`); } }; const timer = window.setInterval(() => void poll(), 3_000); void poll(); return () => { cancelled = true; window.clearInterval(timer); }; }, [feedbackProgress, loadSemanticState, selected]);
  const respondToCodexRequest = async (request: MobileCodexRequest, input: { decision?: string; answers?: Record<string, string> }) => { if (!selected || request.responseSent) return; setRequestSendingId(request.requestId); try { await mobileApi.respondToCodexRequest(selected.id, request.requestId, { revision: request.revision, ...input }); setRequests(current => current.map(currentRequest => currentRequest.requestId === request.requestId ? { ...currentRequest, responseSent: true } : currentRequest)); setError(""); } catch (cause) { setError(`Unable to answer Codex request: ${errorMessage(cause)}`); } finally { setRequestSendingId(undefined); } };
  const returnToWorkbench = () => { setSelected(undefined); setReview(undefined); setPreparedAttachments([]); };
  useEffect(() => { const workstreamId = new URLSearchParams(window.location.search).get("workstream"); const target = workstreamId && workstreams.find(item => item.id === workstreamId); if (target && !selected) void open(target); }, [selected, workstreams]);
  const focusedObservationId = new URLSearchParams(window.location.search).get("reply") ?? undefined;
  useEffect(() => { if (!focusedObservationId || !observations.some(item => item.id === focusedObservationId)) return; document.getElementById(`reply-observation-${focusedObservationId}`)?.focus(); }, [focusedObservationId, observations]);
  return <main className="mobile-workbench">{error && <p role="alert">{error}</p>}<button className="mobile-secondary" onClick={() => void enableWebPush().then(() => setPushNotice("SUBSCRIBED"), cause => setError(`Unable to enable Web Push: ${errorMessage(cause)}`))}>开启本设备通知</button>{pushNotice === "SUBSCRIBED" && <><button className="mobile-secondary" onClick={() => void mobileApi.testPush().catch(cause => setError(`Unable to test Web Push: ${errorMessage(cause)}`))}>发送测试通知</button><button className="mobile-secondary" onClick={() => void disableWebPush().then(() => setPushNotice("SUPPORTED_NOT_SUBSCRIBED"), cause => setError(`Unable to disable Web Push: ${errorMessage(cause)}`))}>关闭本设备通知</button></>}<p className="mobile-note">通知状态：{pushNotice === "UNSUPPORTED" ? "当前浏览器不支持" : pushNotice === "DENIED" ? "浏览器已拒绝" : pushNotice === "NOT_REQUESTED" ? "尚未请求权限" : pushNotice === "SUBSCRIBED" ? "已启用" : "支持但尚未订阅"}</p>{!selected && <WorkstreamList items={workstreams} onOpen={item => void open(item)} />}{selected && review ? <HandoffReview review={review} direction={reviewDirection} message={message} attachments={preparedAttachments} onMessageChange={setMessage} onApprove={() => void approve()} onSend={() => void send()} onRefresh={() => void refreshHandoff()} onBack={review.status === "READY" ? () => setReview(undefined) : undefined} /> : null}{selected && !review ? <><ChatGptReplyObservations observations={observations} focusedObservationId={focusedObservationId} onPrepare={observation => void prepareObservation(observation)} onRead={observation => void markObservationRead(observation)} onHandled={observation => void markObservationRead(observation, true)} /><ReviewResults workstreamName={selected.name} results={results} onBack={returnToWorkbench} onRefresh={() => void refreshSelected()} onPrepare={result => void prepare(result)} onPrepareCodex={(result, draft, attachmentIds, attachments) => void prepareCodex(result, draft, attachmentIds, attachments)} feedbacks={feedbacks} onFeedbackChange={(runId, value) => setFeedbacks(current => ({ ...current, [runId]: value }))} onSendFeedback={result => void sendFeedback(result)} onRecoverFeedback={runId => void recoverFeedbackResult(runId)} feedbackSendingRunId={feedbackSendingRunId} feedbackWaitingRunId={feedbackWaitingRunId} feedbackProgress={feedbackProgress} feedbackRecoveryNotice={feedbackRecoveryNotice} /><CodexRequests requests={requests} onRespond={(request, input) => void respondToCodexRequest(request, input)} sendingRequestId={requestSendingId} /><HistoryPanels chat={chat} codex={codex} loading={historyLoading} notice={historyNotice} onLoad={() => void loadHistory()} /></> : null}</main>;
}
