import { useState } from "react";
import type { ChatHistory, CodexHistory, MobileAttachment, MobileCodexRequest, MobileFeedbackProgress, MobileReplyObservation, MobileReview, MobileReviewResult, MobileWorkstream } from "./api";

function statusSummary(item: MobileWorkstream) { if (item.attentionCount > 0) return "等待你处理"; if (item.codexStatus === "RUNNING" || item.chatgptStatus === "RUNNING") return "电脑正在继续执行"; return "暂无待处理事项"; }
function attachmentStatus(value: string) { if (value === "VERIFIED") return "已验证"; if (value === "MISMATCH") return "校验不匹配"; if (value === "ERROR") return "校验失败"; if (value === "NOT_PROVIDED") return "未提供校验"; return "状态待确认"; }
function choiceLabel(choice: { id: string; label: string }) { if (choice.id === "accept") return "允许这一次"; if (choice.id === "decline") return "拒绝"; if (choice.id === "cancel") return "取消"; return choice.label; }
function attentionCopy(kind: string) { switch (kind) { case "CHATGPT_REPLY_OBSERVED": return ["ChatGPT 有新回复", "当前精确对话中观察到新回复，等待你查看。"]; case "CHATGPT_RESULT_READY": return ["ChatGPT 有新结果", "最新完整回复已保留，等待你审阅。"]; case "CODEX_RESULT_READY": return ["Codex 有新结果", "最新完整结果已保留，等待你审阅。"]; case "CODEX_STRUCTURED_REQUEST": return ["Codex 需要你处理", "当前结构化请求正在等待你的决定。"]; case "HANDOFF_FAILED": return ["交付需要检查", "交付失败，尚未自动重试。"]; case "DELIVERY_UNCERTAIN": return ["交付状态待确认", "Router 尚未证明交付已完成；不会自动重试。"]; default: return ["状态需要确认", "当前 Workstream 有需要你查看的状态。"]; } }

export function ChatGptReplyObservations({ observations, focusedObservationId, onPrepare, onRead, onHandled }: { observations: MobileReplyObservation[]; focusedObservationId?: string; onPrepare: (observation: MobileReplyObservation) => void; onRead: (observation: MobileReplyObservation) => void; onHandled: (observation: MobileReplyObservation) => void }) { if (!observations.length) return null; return <section className="mobile-reply-observations" aria-label="ChatGPT reply observations"><h2>ChatGPT 有新回复</h2><p className="mobile-note">这些是当前精确 ChatGPT 对话的完整可读回复。它们不要求 Router 已证明由哪一次 ProviderRun 产生。</p>{observations.map(observation => <article className="mobile-result-card" id={`reply-observation-${observation.id}`} data-deep-link-focus={observation.id === focusedObservationId || undefined} tabIndex={-1} key={observation.id}><p className="mobile-state">{observation.handledAt ? "已处理" : observation.readAt ? "已读" : "未读"} · 通知：{observation.pushRenderedAt ? "PWA 已执行通知展示（系统横幅无回执）" : observation.pushState === "SENT" ? "Router 已提交通知；尚未收到 PWA 展示回执（不能据此确认手机横幅）" : observation.pushState === "NO_SUBSCRIPTION" ? "本设备未订阅" : observation.pushState === "FAILED" ? "发送未成功，回复仍保留" : "等待发送"}</p><pre className="mobile-result-text">{observation.text}</pre>{!observation.readAt && <button className="mobile-secondary" onClick={() => onRead(observation)}>标为已读</button>}{observation.markerText?.trim() ? <><p className="mobile-note">识别到唯一的 &lt;CODEX_HANDOFF&gt;；仍需审阅、批准、发送。</p><button className="mobile-primary" disabled={Boolean(observation.handledAt)} onClick={() => onPrepare(observation)}>审阅并转发指令</button></> : <><p className="mobile-note">没有唯一的 &lt;CODEX_HANDOFF&gt;；不会自动生成或发送 Handoff。</p><button className="mobile-secondary" disabled={Boolean(observation.handledAt)} onClick={() => onHandled(observation)}>标为已处理</button></>}</article>)}</section>; }

export function WorkstreamList({ items, selectedId, onOpen }: { items: MobileWorkstream[]; selectedId?: string; onOpen: (item: MobileWorkstream) => void }) {
  const attention = items.flatMap(item => item.attentionItems.map(itemAttention => ({ item, itemAttention })));
  return <section className="mobile-overview" aria-label="Workbench overview"><div className="mobile-kicker">AI WORK ROUTER</div><h1>Workbench</h1><p className="mobile-subtitle">{attention.length ? `${attention.length} 件需要你处理 · 其余工作继续在电脑运行` : "其余工作继续在电脑运行"}</p>{attention.map(({ item, itemAttention }, index) => { const [title, detail] = attentionCopy(itemAttention.kind); return <button className="mobile-attention-card" key={`attention-${item.id}-${itemAttention.kind}-${index}`} onClick={() => onOpen(item)}><strong>等待你 · {title}</strong><span>{item.name}</span><p>{detail}</p><em>查看 →</em></button>; })}<h2>最近 Workstreams</h2><div className="mobile-workstream-list">{items.map(item => <button className={selectedId === item.id ? "selected" : ""} key={item.id} onClick={() => onOpen(item)}><strong>{item.name}</strong><span>{statusSummary(item)}</span></button>)}</div><p className="mobile-note">历史与技术状态只在进入 Workstream 后按需查看。</p></section>;
}

export function HistoryPanels({ chat, codex, loading, notice, onLoad }: { chat?: ChatHistory; codex?: CodexHistory; loading: boolean; notice: string; onLoad: () => void }) { return <details className="mobile-technical-details" onToggle={event => { if ((event.currentTarget as HTMLDetailsElement).open) onLoad(); }}><summary>技术详情与只读历史</summary>{loading && <p className="mobile-note">正在读取只读历史…</p>}{notice && <p className="mobile-note">{notice}</p>}{(chat || codex) && <><section><h2>ChatGPT 历史</h2><p className="mobile-note">完整性：{chat?.completeness ?? "待确认"}</p>{chat?.messages.map(item => <article key={item.id}><strong>{item.role}</strong><pre>{item.text}</pre></article>)}</section><section><h2>Codex 只读历史</h2>{codex?.history.filter(item => item.text).map(item => <article key={item.id}><strong>{item.kind}</strong><pre>{item.text}</pre></article>)}</section></>}</details>; }

function AttachmentList({ attachments, selected, onChange, locked }: { attachments: MobileAttachment[]; selected: Record<string, boolean>; onChange?: (id: string, checked: boolean) => void; locked?: boolean }) { return <div className="mobile-attachments">{attachments.length ? attachments.map(attachment => { const eligible = attachment.integrityStatus !== "MISMATCH" && attachment.integrityStatus !== "ERROR"; return <label className="mobile-attachment" key={attachment.id}><input aria-label={`Include ${attachment.filename}`} type="checkbox" checked={selected[attachment.id] ?? false} disabled={locked || !eligible} onChange={event => onChange?.(attachment.id, event.target.checked)} /><span><strong>{attachment.filename}</strong><small>{attachmentStatus(attachment.integrityStatus)}{attachment.warnings?.length ? ` · ${attachment.warnings.join("；")}` : ""}</small></span></label>; }) : <p className="mobile-note">没有可选择的本地附件。</p>}</div>; }

function CodexHandoffDraft({ result, onPrepare }: { result: MobileReviewResult; onPrepare: (draft: string, attachmentIds: string[], attachments: MobileAttachment[]) => void }) {
  const [draft, setDraft] = useState(result.markerText?.trim() || result.text); const attachments = result.attachments ?? []; const [selected, setSelected] = useState<Record<string, boolean>>(() => Object.fromEntries(attachments.map(attachment => [attachment.id, attachment.defaultSelected && attachment.integrityStatus !== "MISMATCH" && attachment.integrityStatus !== "ERROR"])));
  return <section className="mobile-codex-draft" aria-label="Prepare Codex result handoff"><div className="mobile-contract">来源：刚刚审阅的完整 Codex 最终回复。默认只把你确认的结论和选中的本地附件送回当前 Workstream 的 ChatGPT。</div><label>将发送的结论 · 可编辑<textarea aria-label="Draft for ChatGPT" value={draft} onChange={event => setDraft(event.target.value)} /></label><h3>将发送的附件 · 可取消选择</h3><AttachmentList attachments={attachments} selected={selected} onChange={(id, checked) => setSelected(current => ({ ...current, [id]: checked }))} /><p className="mobile-note mobile-warning">校验不匹配或失败的附件不会自动选中；未提供校验是否可选，由已批准的产品规则决定。</p><button className="mobile-primary" disabled={!draft.trim()} onClick={() => onPrepare(draft, attachments.filter(attachment => selected[attachment.id]).map(attachment => attachment.id), attachments.filter(attachment => selected[attachment.id]))}>审阅结论和附件</button></section>;
}

function ResultCard({ result, onPrepare, onPrepareCodex, feedback, onFeedbackChange, onSendFeedback, onRecoverFeedback, feedbackSending, feedbackWaiting, feedbackProgress, feedbackRecoveryNotice }: { result: MobileReviewResult; onPrepare: (result: MobileReviewResult) => void; onPrepareCodex: (result: MobileReviewResult, draft: string, attachmentIds: string[], attachments: MobileAttachment[]) => void; feedback: string; onFeedbackChange: (value: string) => void; onSendFeedback: () => void; onRecoverFeedback: (runId: string) => void; feedbackSending: boolean; feedbackWaiting: boolean; feedbackProgress?: MobileFeedbackProgress; feedbackRecoveryNotice?: string }) {
  const isChatGpt = result.provider === "CHATGPT"; const [rejecting, setRejecting] = useState(false); const [preparingCodex, setPreparingCodex] = useState(false); const title = isChatGpt ? "ChatGPT 最新回复待审阅" : "Codex 结果待审阅"; const target = isChatGpt ? "ChatGPT" : "Codex";
  const codexConclusion = result.markerText?.trim() || result.text;
  const codexAttachments = result.attachments ?? [];
  const selectedCodexAttachments = Object.fromEntries(codexAttachments.map(attachment => [attachment.id, attachment.defaultSelected && attachment.integrityStatus !== "MISMATCH" && attachment.integrityStatus !== "ERROR"]));
  const feedbackLocked = feedbackSending || (feedbackWaiting && (!isChatGpt || feedbackProgress?.phase !== "DELIVERY_FAILED"));
  const recoveryRunId = feedbackProgress?.phase === "DELIVERY_UNCONFIRMED" ? feedbackProgress.runId : result.recoveryRunId;
  const feedbackTitle = feedbackProgress?.phase === "DELIVERY_FAILED" ? "修改意见未完成 · 不存在 Handoff" : feedbackProgress?.phase === "DELIVERY_UNCONFIRMED" ? "修改意见送达未确认 · 不存在 Handoff" : feedbackProgress?.phase === "REVISED_RESULT_READY" ? "新的完整结果已保留 · 不存在 Handoff" : "修改意见已发送 · 不存在 Handoff";
  return <article className="mobile-result-card" aria-label={`${target} complete result`}><h2>{title}</h2><p className="mobile-state">{result.reviewedAt ? "已审阅 · 当前完整结果仍可回看" : "当前完整结果已保留 · 等待你确认"}</p><div className="mobile-contract">刷新或切换 Workstream 后仍能回来审阅；新的完整结果被精确确认前，不会替换当前结果。</div><h3>完整{isChatGpt ? "回复" : "最终回复"} · 可滚动，不截断</h3><pre className="mobile-result-text">{result.text}</pre>{isChatGpt ? <>{result.markerText?.trim() ? <><h3>识别到的 Codex 指令</h3><pre className="mobile-extracted">{result.markerText}</pre><p className="mobile-note">只允许转发这一段；无法确定边界时，Router 禁止转发。</p><button className="mobile-primary" onClick={() => onPrepare(result)}>只转发指令</button></> : <p className="mobile-note mobile-warning">未能确定可转发的 Codex 指令边界，因此不能创建 Handoff；你仍可打回整条回复。</p>}{recoveryRunId && <div className="mobile-waiting" role="status"><strong>有一条完整结果尚未保留</strong><p>Router 只会重新读取这一条精确结果；不会自动重试、发送消息或创建 Handoff。</p>{feedbackRecoveryNotice && <p className="mobile-note mobile-warning">{feedbackRecoveryNotice}</p>}<button className="mobile-secondary" onClick={() => onRecoverFeedback(recoveryRunId)}>重新读取这条完整结果</button></div>}</> : preparingCodex ? <CodexHandoffDraft result={result} onPrepare={(draft, attachmentIds, attachments) => onPrepareCodex(result, draft, attachmentIds, attachments)} /> : <><h3>{result.markerText?.trim() ? "建议转发的结论" : "将送审的完整结论"}</h3><pre className="mobile-extracted">{codexConclusion}</pre><h3>电脑本地附件 · 发送前再次 SHA256</h3><AttachmentList attachments={codexAttachments} selected={selectedCodexAttachments} locked /><p className="mobile-note">只有进入下一步并确认的结论与附件才会跨系统发送。</p><button className="mobile-primary" onClick={() => setPreparingCodex(true)}>转发结论 + 附件</button></>}{!rejecting ? <button className="mobile-secondary" onClick={() => setRejecting(true)}>打回 {target}</button> : <section className="mobile-feedback" aria-label={`Reject ${target} result`}><h3>告诉 {target} 需要怎么改</h3><p className="mobile-state mobile-reject">否决当前结果 · 不创建 {isChatGpt ? "Codex" : "ChatGPT"} Handoff</p><div className="mobile-contract mobile-reject-contract">当前完整结果继续保留；反馈只会送回这个 Workstream 的当前 exact {target} 工作，不会按标题或最近记录猜目标。</div><textarea aria-label={`${target} revision feedback`} value={feedback} onChange={event => onFeedbackChange(event.target.value)} disabled={feedbackLocked} /><button className="mobile-primary" onClick={onSendFeedback} disabled={feedbackLocked || !feedback.trim()}>{feedbackSending ? "正在确认送达…" : `打回并告诉 ${target}`}</button></section>}{feedbackWaiting && <div className="mobile-waiting" role="status"><strong>{feedbackTitle}</strong><p>{feedbackProgress?.message ?? `当前完整结果已否决但继续保留。Router 正等待同一个 exact ${target} 工作的下一条完整结果；到达后会重新进入审阅。`}</p></div>}</article>;
}

export function ReviewResults({ workstreamName, results, onBack, onRefresh, onPrepare, onPrepareCodex, feedbacks, onFeedbackChange, onSendFeedback, onRecoverFeedback, feedbackSendingRunId, feedbackWaitingRunId, feedbackProgress, feedbackRecoveryNotice }: { workstreamName: string; results: MobileReviewResult[]; onBack: () => void; onRefresh: () => void; onPrepare: (result: MobileReviewResult) => void; onPrepareCodex: (result: MobileReviewResult, draft: string, attachmentIds: string[], attachments: MobileAttachment[]) => void; feedbacks: Record<string, string>; onFeedbackChange: (runId: string, value: string) => void; onSendFeedback: (result: MobileReviewResult) => void; onRecoverFeedback: (runId: string) => void; feedbackSendingRunId?: string; feedbackWaitingRunId?: string; feedbackProgress?: { sourceRunId: string; progress: MobileFeedbackProgress }; feedbackRecoveryNotice?: { sourceRunId: string; message: string } }) { return <section className="mobile-workstream" aria-label="Reviewable provider results"><div className="mobile-workstream-heading"><button className="mobile-back" aria-label="Return to Workbench" onClick={onBack}>‹ Workbench</button><h1>{workstreamName}</h1><p className="mobile-subtitle">从最新完整结果开始审阅；跨系统动作始终经过人工确认。</p><button className="mobile-secondary" onClick={onRefresh}>刷新当前状态</button><p className="mobile-note">只会重新读取当前精确 ChatGPT 结果；不会发送消息或创建 Handoff。</p></div>{results.map(result => <ResultCard key={result.runId} result={result} onPrepare={onPrepare} onPrepareCodex={onPrepareCodex} feedback={feedbacks[result.runId] ?? ""} onFeedbackChange={value => onFeedbackChange(result.runId, value)} onSendFeedback={() => onSendFeedback(result)} onRecoverFeedback={onRecoverFeedback} feedbackSending={feedbackSendingRunId === result.runId} feedbackWaiting={feedbackWaitingRunId === result.runId} feedbackProgress={feedbackProgress?.sourceRunId === result.runId ? feedbackProgress.progress : undefined} feedbackRecoveryNotice={feedbackRecoveryNotice?.sourceRunId === result.runId ? feedbackRecoveryNotice.message : undefined} />)}{!results.length && <p className="mobile-empty">当前没有可审阅的完整结果。</p>}</section>; }

function requestTitle(request: MobileCodexRequest) { if (request.method.includes("commandExecution")) return "Codex 需要你批准命令"; if (request.method.includes("fileChange")) return "Codex 需要你审阅文件变更"; return "Codex 需要你的输入"; }
function CodexRequestCard({ request, onRespond, sending }: { request: MobileCodexRequest; onRespond: (input: { decision?: string; answers?: Record<string, string> }) => void; sending: boolean }) { const [answers, setAnswers] = useState<Record<string, string>>({}); const questions = request.questions ?? []; const canSendAnswers = questions.length > 0 && questions.every(question => !question.required || Boolean(answers[question.id]?.trim())); return <article className="mobile-request-card" aria-label="Codex explicitly requests input"><h2>{requestTitle(request)}</h2><p className="mobile-state">{request.responseSent ? "回应已送达 · 等待当前 turn 继续" : "当前 turn 已暂停 · 等待你批复"}</p><div className="mobile-contract">这不是新的任务，也不是 Router Handoff。只有 app-server 收到的当前 exact Codex request 才会出现在这里；你的决定只回应这一次。</div>{request.reason && <pre className="mobile-request-detail">{request.reason}</pre>}{questions.map(question => <label key={question.id}>{question.label}<textarea aria-label={question.label} placeholder={question.placeholder} value={answers[question.id] ?? ""} disabled={sending || request.responseSent} onChange={event => setAnswers(current => ({ ...current, [question.id]: event.target.value }))} /></label>)}<div className="mobile-request-actions">{(request.choices ?? []).map(choice => <button className={choice.id === "accept" ? "mobile-primary" : "mobile-secondary"} key={choice.id} disabled={sending || request.responseSent} onClick={() => onRespond({ decision: choice.id })}>{choiceLabel(choice)}</button>)}</div>{questions.length > 0 && <button className="mobile-primary" disabled={sending || request.responseSent || !canSendAnswers} onClick={() => onRespond({ answers })}>{sending ? "正在发送回应…" : "回复并继续"}</button>}<p className="mobile-note">不会创建新的 ProviderRun 或 Handoff，也不会提供“本会话全部允许”。</p></article>; }
export function CodexRequests({ requests, onRespond, sendingRequestId }: { requests: MobileCodexRequest[]; onRespond: (request: MobileCodexRequest, input: { decision?: string; answers?: Record<string, string> }) => void; sendingRequestId?: string }) { if (!requests.length) return null; return <section className="mobile-codex-requests" aria-label="Codex requests">{requests.map(request => <CodexRequestCard key={request.requestId} request={request} onRespond={input => onRespond(request, input)} sending={sendingRequestId === request.requestId} />)}</section>; }

export function HandoffReview({ review, direction, message, attachments, onMessageChange, onApprove, onSend, onRefresh, onBack }: { review: MobileReview; direction: "CHATGPT_TO_CODEX" | "CODEX_TO_CHATGPT"; message: string; attachments: MobileAttachment[]; onMessageChange: (message: string) => void; onApprove: () => void; onSend: () => void; onRefresh: () => void; onBack?: () => void }) { const target = direction === "CHATGPT_TO_CODEX" ? "Codex" : "ChatGPT"; const sent = review.status === "SENT"; const sending = review.status === "SENDING"; const failed = review.status === "FAILED"; const approved = review.status === "APPROVED"; return <section className="mobile-handoff-review" aria-label="Handoff review">{onBack && <button className="mobile-back" onClick={onBack}>‹ 返回完整结果</button>}<h1>{sent ? `已发送给 ${target}` : sending ? "正在确认送达" : failed ? "交付未完成" : approved ? "内容已批准" : direction === "CHATGPT_TO_CODEX" ? "只转发识别出的指令" : "准备送回 ChatGPT"}</h1><p className="mobile-state">{sent ? "Handoff 与执行状态分开" : sending ? "交付状态待确认" : failed ? "交付失败" : approved ? `步骤 2 / 2 · 发送给 ${target}` : "步骤 1 / 2 · 审阅 payload"}</p>{(sending || sent || failed) && <button className="mobile-secondary" onClick={onRefresh}>刷新当前状态</button>}{sent ? <><div className="mobile-sent-card"><strong>Handoff · 已发送</strong><p>只交付了已批准的内容；未选择的解释、正文或附件没有被转发。</p></div><div className="mobile-provider-run"><strong>{target} 执行 · 状态待确认</strong><p>这是独立的 ProviderRun 状态。Handoff 已发送不等于 {target} 已完成。</p></div><p className="mobile-note">不会自动继续下一次 ChatGPT ↔ Codex relay；新的完整结果仍需重新审阅。</p></> : sending ? <><div className="mobile-provider-run"><strong>交付状态待确认</strong><p>正在确认送达；Handoff 尚未呈现为已发送。不会自动重试。</p></div><p className="mobile-note">刷新会重新读取当前 Workstream 的结果、Codex 请求和相关交付状态。</p></> : failed ? <><div className="mobile-provider-run"><strong>Handoff 未确认送达</strong><p>Router 已获得明确失败结果。不会自动重试，也不会把交付显示为已发送。</p></div></> : <><div className="mobile-contract">来源已固定为刚刚审阅的完整结果；只有这里确认的内容会进入下一步。</div><label>{approved ? "已批准的 payload" : "将发送的 payload · 可审阅 / 可编辑"}<textarea aria-label="Approved payload" value={message} onChange={event => onMessageChange(event.target.value)} disabled={review.status !== "READY"} /></label>{direction === "CODEX_TO_CHATGPT" && <><h3>已选附件</h3><AttachmentList attachments={attachments} selected={Object.fromEntries(attachments.map(item => [item.id, true]))} locked /></>}{review.status === "READY" && <button className="mobile-primary" onClick={onApprove}>批准这段内容</button>}{approved && <button className="mobile-primary" onClick={onSend}>发送给当前 {target}</button>}{approved && <p className="mobile-note">批准后内容和附件已锁定；为避免静默解锁，不能返回编辑。</p>} {review.status === "READY" && <p className="mobile-note">返回完整结果不会改变 payload；只有批准后才能真正发送。</p>}</>}</section>; }
