import {t as uiText,tc,useLanguage,getLanguage} from "../../i18n";
import {useEffect,useRef,useState} from "react";
import * as Dialog from "@radix-ui/react-dialog";
import {ChevronLeft,Smartphone,Trash2,Wifi} from "lucide-react";
import {CopyAction} from "./NativeReaderActions";
import {deploymentInstructions,type ConnectionMethod} from "./mobileDeployment";
import {invoke} from "@tauri-apps/api/core";
import {HostedConnection,type HostedApi} from "./HostedConnection";
export type Availability={state:string;localReady:boolean;tunnelReady:boolean;publicReady:boolean;recoveryAllowed:boolean;checkedAt:number;recoveryCount:number;setupPending?:boolean};
type Device={id:string;label:string;createdAt:number;expiresAt:number};
export type ConnectionView={method:string;origin:string|null;port:number;configured:boolean};
export type WebAccessApi={connection?:()=>Promise<ConnectionView>;configure?:(input:{method:ConnectionMethod;origin:string})=>Promise<ConnectionView>;devices:()=>Promise<Device[]>;issue:(replaceDeviceId?:string)=>Promise<{code:string;expiresAt:number}>;revoke:(deviceId:string)=>Promise<unknown>;url:()=>Promise<string|null>;availability?:()=>Promise<Availability>;retry?:()=>Promise<unknown>;setup?:()=>Promise<unknown>};
const desktopHostedApi:HostedApi={status:()=>invoke('hosted_connection_status'),redeem:code=>invoke('hosted_connection_redeem',{input:{code}})};
const desktopApi:WebAccessApi={connection:()=>invoke("mobile_connection_view"),configure:input=>invoke("mobile_connection_configure",{input}),availability:()=>invoke("web_availability_status"),retry:()=>invoke("web_availability_retry"),setup:()=>invoke("web_availability_setup"),devices:()=>invoke("web_paired_devices"),issue:replaceDeviceId=>invoke("web_pairing_code",{replaceDeviceId:replaceDeviceId??null}),revoke:deviceId=>invoke("web_revoke_device",{deviceId}),url:()=>invoke<string|null>("codex_notifications_web_url").then(value=>value?new URL("/mobile",value).href:null)};
export function DesktopWebAccess({api=desktopApi,openRequest=0,hostedApi}:{api?:WebAccessApi;openRequest?:number;hostedApi?:HostedApi}){
 useLanguage();const[hostedEditing,setHostedEditing]=useState(false),[hostedAvailable,setHostedAvailable]=useState(false),[selfMode,setSelfMode]=useState(false);
 const[connection,setConnection]=useState<ConnectionView|null>(null),[editing,setEditing]=useState(false),[method,setMethod]=useState<ConnectionMethod>("TAILSCALE_FUNNEL"),[origin,setOrigin]=useState("");
 const[replacement,setReplacement]=useState("");
 const[removing,setRemoving]=useState<Device|null>(null);const[open,setOpen]=useState(false),[devices,setDevices]=useState<Device[]>([]),[pairing,setPairing]=useState<{code:string;expiresAt:number}|null>(null),[url,setUrl]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[time,setTime]=useState(Date.now());const pending=useRef(false);const[availability,setAvailability]=useState<Availability|null>(null);
 useEffect(()=>{if(!open)return;let alive=true;const check=()=>void api.availability?.().then(s=>{if(alive)setAvailability(s);}).catch(()=>{if(alive)setAvailability(null);});check();void api.connection?.().then(c=>{if(alive){setConnection(c);setEditing(!c.configured);setOrigin(c.origin??"");if(c.method!=="NONE"&&c.method!=="HOSTED")setMethod(c.method as ConnectionMethod);}}).catch(()=>{if(alive)setError(uiText("连接配置暂时不可用。"));});void Promise.all([api.devices(),api.url()]).then(([d,u])=>{if(alive){setDevices(d);setUrl(u);}}).catch(()=>{if(alive)setError(uiText("网页登录设置暂时不可用，请重试。"));});const timer=setInterval(()=>{setTime(Date.now());check();void api.devices().then(d=>{if(alive)setDevices(d);}).catch(()=>{});},5000);return()=>{alive=false;clearInterval(timer);};},[open,api]);
 async function act(work:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError(null);try{await work();}catch{setError(uiText("操作未完成，请检查电脑端状态后重试。"));}finally{pending.current=false;setBusy(false);}}
 useEffect(()=>{if(openRequest)setOpen(true);},[openRequest]);
 useEffect(()=>{if(replacement&&!devices.some(device=>device.id===replacement)){setReplacement("");setPairing(null);}},[devices,replacement]);
 async function configure(){if(!api.configure)return;await act(async()=>{try{const c=await api.configure!({method,origin});setConnection(c);setOrigin(c.origin??"");setUrl(c.origin?new URL('/mobile',c.origin).href:null);setEditing(false);setPairing(null);}catch(e){setError(String(e).includes('MOBILE_ORIGIN')?uiText("请输入不含路径的 HTTPS 网址。"):String(e).includes('TAILSCALE_ORIGIN')?uiText("请填写 Tailscale 提供的 .ts.net 网址。"):uiText("未能验证这个入口，原连接已保留。请检查转发和 HTTPS 配置。"));}});}
 const remaining=pairing?Math.max(0,Math.ceil(pairing.expiresAt-Date.now()/1000)):0;
 return <><button type="button" className="v3-notification-entry v4-web-access-entry" onClick={()=>setOpen(true)}>{uiText("手机/网页登录")}</button><Dialog.Root open={open} onOpenChange={value=>{if(!busy){setOpen(value);if(!value)setPairing(null);}}}><Dialog.Portal><Dialog.Overlay className="v3-role-dialog-overlay"/><Dialog.Content className="v3-role-dialog v4-web-access-dialog r2-device-panel" aria-describedby={undefined}><header><Dialog.Close asChild><button type="button" className="r2-icon" aria-label={uiText("关闭设备设置")} disabled={busy}><ChevronLeft size={20}/></button></Dialog.Close><Dialog.Title>{uiText("设备")}</Dialog.Title></header><div className="v5-access-body">
  <section className="r2-device-connection"><Wifi size={20}/><strong>{availability?.state==="CONFIG_REQUIRED"?uiText("未配置手机连接"):availability?.publicReady?uiText("网页已连接"):availability?.state==="ADMIN_SETUP_REQUIRED"?uiText("需配置自动恢复"):availability?.state==="PUBLIC_UNREACHABLE"?uiText("公网暂时不可用"):uiText("检查连接中")}</strong>{!availability?.publicReady&&api.retry&&<button type="button" disabled={busy} onClick={()=>void act(async()=>{await api.retry?.();})}>{uiText("检查连接")}</button>}</section>
  {(hostedApi||api===desktopApi)&&<HostedConnection api={hostedApi??desktopHostedApi} onModeChange={setHostedEditing} onAvailable={setHostedAvailable} onActivated={async()=>{const c=await api.connection?.();if(c){setConnection(c);setOrigin(c.origin??'');setUrl(c.origin?new URL('/mobile',c.origin).href:null);setEditing(false);setSelfMode(false);setPairing(null);}}}/>}
  {api.connection&&!hostedEditing&&(!hostedAvailable||selfMode||connection?.configured&&connection.method!=="HOSTED")&&<section className="r2-remote-setup" aria-label={uiText("远程连接配置")}>{editing?<form onSubmit={e=>{e.preventDefault();void configure();}}><label>{uiText("连接方式")}<select aria-label={uiText("连接方式")} value={method} disabled={busy} onChange={e=>setMethod(e.target.value as ConnectionMethod)}><option value="TAILSCALE_FUNNEL">Tailscale Funnel</option><option value="TAILSCALE_SERVE">{uiText("Tailscale Serve · 私有网络")}</option><option value="CLOUDFLARE">Cloudflare Tunnel</option><option value="CUSTOM_HTTPS">{uiText("已有 HTTPS 入口")}</option></select></label><label>{uiText("HTTPS 网址")}<input type="url" aria-label={uiText("HTTPS 网址")} placeholder="https://" value={origin} disabled={busy} onChange={e=>setOrigin(e.target.value)}/></label><div className="r2-deploy-prompt"><span>{uiText("交给 Agent 配置")}</span><CopyAction text={deploymentInstructions(method,origin,connection?.port??47114)} label={uiText("复制部署指令")} onError={()=>setError(uiText("指令未复制，请重试。"))}/></div>{connection?.configured&&<p className="v4-meta">{uiText("更换网址后需在新网址配对。")}</p>}<button className="r2-action" type="submit" disabled={busy||!origin.trim()}>{busy?uiText("验证中…"):uiText("验证并保存")}</button>{connection?.configured&&<button type="button" disabled={busy} onClick={()=>setEditing(false)}>{uiText("取消")}</button>}</form>:<button type="button" disabled={busy} onClick={()=>setEditing(true)}>{uiText("更换连接")}</button>}</section>}
  {hostedAvailable&&!hostedEditing&&!selfMode&&(!connection?.configured||connection.method==="HOSTED")&&<button type="button" disabled={busy} onClick={()=>{setSelfMode(true);setEditing(true);if(connection?.method==="HOSTED")setOrigin("");}}>{uiText("自行配置")}</button>}
  {availability?.state==="ADMIN_SETUP_REQUIRED"&&api.setup&&<button type="button" disabled={busy||availability.setupPending} onClick={()=>void act(async()=>{await api.setup?.();})}>{availability.setupPending?uiText("等待管理员确认…"):uiText("启用自动恢复")}</button>}
  {(url||!api.connection)&&<section className="r2-device-pair" aria-label={uiText("手机配对")}><h3>{uiText("添加设备")}</h3>{url?<div className="r2-device-url"><a href={url} target="_blank" rel="noreferrer noopener">{url}</a><CopyAction text={url} label={uiText("复制网址")} onError={()=>setError(uiText("网址未复制，请选择链接复制。"))}/></div>:<p role="status">{uiText("网页地址未配置")}</p>}<p className="v4-meta">{uiText("手机打开网址，输入配对码。")}</p>{devices.length>0&&<label className="r2-pairing-target">{uiText("配对方式")}<select aria-label={uiText("配对方式")} value={replacement} disabled={busy} onChange={e=>{setReplacement(e.target.value);setPairing(null);}}><option value="">{uiText("添加设备")}</option>{devices.map(device=><option key={device.id} value={device.id}>{uiText("替换 {0}",device.label)} · {new Date(device.createdAt*1000).toLocaleString(getLanguage())}</option>)}</select></label>}<button className="r2-action" type="button" disabled={busy||!url||devices.length>=20&&!replacement} onClick={()=>void act(async()=>{setPairing(await api.issue(replacement||undefined));setTime(Date.now());})}>{busy?uiText("正在处理…"):pairing?uiText("生成新配对码"):uiText("生成配对码")}</button>{replacement&&<p className="v4-meta">{uiText("新登录成功后才替换旧记录。")}</p>}{devices.length>=20&&!replacement&&<p className="v4-meta">{uiText("已达 20 台上限，请选择替换旧登录。")}</p>}{pairing&&<><output className="v4-pairing-code" aria-label={uiText("一次性配对码")}>{remaining?pairing.code:uiText("已过期")}</output><p className="v4-meta" data-clock={time}>{remaining?tc("{0} 分钟内有效 · 使用一次", Math.ceil(remaining/60)):uiText("请生成新码")}</p></>}<p className="v4-meta">{uiText("设备保持登录 90 天，使用时续期。")}</p></section>}
  {(url||devices.length>0||!api.connection)&&<section aria-label={uiText("已登录设备")}><h3>{uiText("已登录设备")}</h3>{devices.length?devices.map(device=><div key={device.id} className="v4-device-row"><Smartphone size={20}/><div><strong>{device.label}</strong><p className="v4-meta">{uiText("至")} {new Date(device.expiresAt*1000).toLocaleDateString(getLanguage())}</p></div><button type="button" className="r2-icon" aria-label={uiText("退出此设备：{0}", device.label)} disabled={busy} onClick={()=>setRemoving(device)}><Trash2 size={18}/></button></div>):<p className="v4-meta">{uiText("暂无已配对设备")}</p>}</section>}{error&&<p role="alert">{uiText(error)}</p>}
 </div></Dialog.Content></Dialog.Portal></Dialog.Root>
 <Dialog.Root open={Boolean(removing)} onOpenChange={value=>{if(!value&&!busy)setRemoving(null);}}><Dialog.Portal><Dialog.Overlay className="v3-role-dialog-overlay"/><Dialog.Content className="r2-confirmation" aria-describedby="r2-revoke-note"><Dialog.Title>{uiText("退出此设备？")}</Dialog.Title><p id="r2-revoke-note">{removing?.label} {uiText("将需要重新配对。")}</p>{error&&<p role="alert">{uiText(error)}</p>}<footer><Dialog.Close asChild><button type="button" disabled={busy}>{uiText("取消")}</button></Dialog.Close><button type="button" className="r2-action r2-danger-action" disabled={busy} onClick={()=>void act(async()=>{if(!removing)return;await api.revoke(removing.id);setDevices(await api.devices());setRemoving(null);})}>{uiText("退出此设备")}</button></footer></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
