import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,describe,expect,it,vi } from "vitest";
import { NotificationDeliveryPanel,type DeliveryApi,type DeliveryView } from "./NotificationDeliveryPanel";
vi.mock("../../mobile/push",()=>({pushSetupState:vi.fn().mockResolvedValue("SUPPORTED_NOT_SUBSCRIBED"),enableWebPush:vi.fn().mockResolvedValue(undefined),disableWebPush:vi.fn().mockResolvedValue(undefined)}));
import { enableWebPush } from "../../mobile/push";
afterEach(cleanup);
function fixture(desktop=true){const view:DeliveryView={account:"agbrio.fixture@gmail.com",recipient:"agbrio.fixture@gmail.com",hasSecret:false,windowsStatus:"ENABLED",channels:[{channel:"WINDOWS",enabled:false},{channel:"EMAIL",enabled:false}],history:[]};return {desktop,settings:vi.fn().mockResolvedValue(view),command:vi.fn().mockResolvedValue("SAVED")} satisfies DeliveryApi;}
describe("notification delivery setup",()=>{
 it("lets first-use Windows send a test before enabling ongoing reminders",async()=>{const api=fixture();const initial=await api.settings();api.settings.mockReset().mockResolvedValueOnce({...initial,windowsStatus:"NOT_INITIALIZED"}).mockResolvedValue(initial);render(<NotificationDeliveryPanel api={api}/>);expect(await screen.findByText("首次使用，请先发送测试通知，然后开启提醒。",{exact:false})).toBeInTheDocument();expect(screen.getByRole("button",{name:"开启 Windows 提醒"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"测试 Windows 通知"}));await waitFor(()=>expect(screen.getByRole("button",{name:"开启 Windows 提醒"})).toBeEnabled());expect(api.command).toHaveBeenCalledExactlyOnceWith({action:"TEST",channel:"WINDOWS"});});
 it("requires a user gesture for browser permission and hides desktop credential setup on web",async()=>{vi.mocked(enableWebPush).mockClear();const api=fixture(false);render(<NotificationDeliveryPanel api={api}/>);await screen.findByText("尚未订阅");expect(enableWebPush).not.toHaveBeenCalled();expect(screen.queryByLabelText("应用专用密码")).not.toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"开启此浏览器推送"}));await waitFor(()=>expect(api.command).toHaveBeenCalledWith({action:"CHANNEL",channel:"WEB",enabled:true}));});
 it("saves the corrected email and clears the password input; no send happens before test",async()=>{const api=fixture();render(<NotificationDeliveryPanel api={api}/>);const input=await screen.findByLabelText("应用专用密码");expect(screen.getByLabelText("收件邮箱")).toHaveValue("agbrio.fixture@gmail.com");expect(screen.getByRole("button",{name:"发送测试邮件"})).toBeDisabled();fireEvent.change(input,{target:{value:"abcdefghijklmnop"}});fireEvent.click(screen.getByRole("button",{name:"保存邮件设置"}));await waitFor(()=>expect(input).toHaveValue(""));expect(api.command).toHaveBeenCalledExactlyOnceWith({action:"EMAIL",account:"agbrio.fixture@gmail.com",recipient:"agbrio.fixture@gmail.com",password:"abcdefghijklmnop"});});
});
