import {t as uiText,tc,useLanguage} from "../../i18n";
import { useEffect, useState } from "react";
import { disableWebPush, enableWebPush, pushSetupState, type PushSetupState } from "../../mobile/push";

export type DeliveryView = { account:string; recipient:string; hasSecret:boolean; windowsStatus:string; channels:{channel:string;enabled:boolean}[]; history:{eventSequence:number;channel:string;status:string;attempts:number;errorCode:string|null;updatedAt:number}[] };
export type DeliveryApi = { desktop:boolean; settings():Promise<DeliveryView>; command(input:unknown):Promise<string> };
const channels:Record<string,string>={get WEB(){return uiText("浏览器");},WINDOWS:"Windows",get EMAIL(){return uiText("邮件");}};
const statuses:Record<string,string>={get PENDING(){return uiText("等待发送");},get SENDING(){return uiText("正在发送");},get SENT(){return uiText("发送通道已接收");},get FAILED(){return uiText("发送失败，等待有限重试");},get UNKNOWN(){return uiText("发送结果不确定，请先核对");},get SKIPPED(){return uiText("未发送");}};
const pushStates:Record<PushSetupState,string>={get UNSUPPORTED(){return uiText("此浏览器不支持推送");},get NOT_REQUESTED(){return uiText("尚未允许通知");},get DENIED(){return uiText("浏览器已拒绝权限，请到站点设置允许");},get SUPPORTED_NOT_SUBSCRIBED(){return uiText("尚未订阅");},get UPDATING(){return uiText("通知组件正在更新");},get SUBSCRIBED(){return uiText("此浏览器已订阅");}};
const errors:Record<string,string>={get EMAIL_APP_PASSWORD_REQUIRED(){return uiText("请先在桌面工具保存 Gmail 应用专用密码。");},get EMAIL_APP_PASSWORD_FORMAT_INVALID(){return uiText("请填写 Google 提供的 16 位应用专用密码。");},get EMAIL_ADDRESS_INVALID(){return uiText("邮箱地址格式不正确。");},get SMTP_REJECTED_CHECK_ACCOUNT(){return uiText("Gmail 拒绝发信，请检查账号及应用专用密码。");},get SMTP_ACCEPTANCE_UNKNOWN(){return uiText("邮件发送结果不确定。请先检查收件箱，避免重复发送。");},get WEB_PUSH_NO_SUBSCRIPTION(){return uiText("尚无浏览器订阅，请先在网页通知入口开启推送。");},get WINDOWS_NOTIFICATIONS_DISABLED(){return uiText("Windows 未允许此工具显示通知，请在系统通知设置中开启。");},get NOTIFICATION_WEB_URL_UNAVAILABLE(){return uiText("尚未配置可访问的通知网页地址。");}};
export function NotificationDeliveryPanel({api}:{api:DeliveryApi}){
 useLanguage();
 const [view,setView]=useState<DeliveryView|null>(null),[account,setAccount]=useState(""),[recipient,setRecipient]=useState(""),[password,setPassword]=useState(""),[push,setPush]=useState<PushSetupState|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let active=true;void api.settings().then(v=>{if(active){setView(v);setAccount(v.account);setRecipient(v.recipient);}}).catch(e=>{if(active)setError(String(e));});if(!api.desktop)void pushSetupState().then(s=>{if(active)setPush(s);}).catch(()=>{if(active)setPush("UNSUPPORTED");});const timer=setInterval(()=>{void api.settings().then(v=>{if(active)setView(v);}).catch(()=>{});},5000);return()=>{active=false;clearInterval(timer);};},[api]);
 async function act(work:()=>Promise<string>){if(busy)return;setBusy(true);setMessage("");setError("");try{setMessage(await work());setView(await api.settings());}catch(e){const raw=String(e).replace(/^Error: /,"");setError(errors[raw]??raw);}finally{setBusy(false);}}
 function channel(name:string){return view?.channels.find(c=>c.channel===name)?.enabled??false;}
 return <section aria-label={uiText("提醒推送")} className="v3-notification-delivery"><h2>{uiText("提醒推送")}</h2><p>{uiText("新结果和明确失败会提醒；普通进度保留在通知列表。开启后从当前时间开始，不补发旧记录。")}</p>
 {error&&<p role="alert">{uiText(error)}</p>}{message&&<p role="status">{uiText(message)}</p>}
 {api.desktop?<p>{uiText("浏览器通知：在「网页通知入口」打开的浏览器里开启。")}{channel("WEB")?uiText(" Router 已启用浏览器发送通道。"):""}</p>:<div><h3>{uiText("浏览器通知")}</h3><p>{push?pushStates[push]:uiText("正在检查权限…")}</p><div className="v3-notification-actions"><button disabled={busy||push==="UNSUPPORTED"||push==="DENIED"} onClick={()=>void act(async()=>{await enableWebPush();await api.command({action:"CHANNEL",channel:"WEB",enabled:true});setPush(await pushSetupState());return uiText("浏览器推送已开启。");})}>{uiText("开启此浏览器推送")}</button><button disabled={busy||push!=="SUBSCRIBED"} onClick={()=>void act(async()=>{await disableWebPush();setPush(await pushSetupState());return uiText("已关闭此浏览器的订阅。");})}>{uiText("关闭此浏览器推送")}</button><button disabled={busy||push!=="SUBSCRIBED"} onClick={()=>void act(async()=>{await api.command({action:"TEST",channel:"WEB"});return uiText("推送服务已接收测试通知，请检查浏览器或系统通知。");})}>{uiText("测试浏览器通知")}</button></div></div>}
 {api.desktop&&view&&<><div><h3>{uiText("Windows 桌面通知")}</h3><p>{view.windowsStatus==="ENABLED"?uiText("Windows 允许此工具通知。"):view.windowsStatus==="NOT_INITIALIZED"?uiText("首次使用，请先发送测试通知，然后开启提醒。"):uiText("Windows 通知不可用或被系统设置禁用。")} {uiText("点击通知会打开对应的 Router 通知。")}</p><div className="v3-notification-actions"><button disabled={busy||view.windowsStatus!=="ENABLED"} onClick={()=>void act(async()=>{await api.command({action:"CHANNEL",channel:"WINDOWS",enabled:!channel("WINDOWS")});return channel("WINDOWS")?uiText("Windows 提醒已关闭。"):uiText("Windows 提醒已开启。");})}>{channel("WINDOWS")?uiText("关闭 Windows 提醒"):uiText("开启 Windows 提醒")}</button><button disabled={busy||!["ENABLED","NOT_INITIALIZED"].includes(view.windowsStatus)} onClick={()=>void act(async()=>{await api.command({action:"TEST",channel:"WINDOWS"});return uiText("已提交 Windows 测试通知。横幅是否显示由系统通知设置决定。");})}>{uiText("测试 Windows 通知")}</button></div></div>
 <details><summary>{uiText("Gmail 邮件提醒 ·")} {channel("EMAIL")?uiText("已开启"):uiText("未开启")}</summary><p>{uiText("固定使用 smtp.gmail.com:465，TLS 加密。主题前缀 [AIWR_EVENT]；邮件包含来源和原文链接，方便 Dot 的新邮件触发规则读取。")}</p><form onSubmit={e=>{e.preventDefault();void act(async()=>{await api.command({action:"EMAIL",account,recipient,password:password||null});setPassword("");return uiText("邮件设置已保存。请先发送测试邮件，再开启提醒。");});}}><label>{uiText("发信 Gmail 账号")}<input type="email" required value={account} disabled={busy} onChange={e=>setAccount(e.target.value)} /></label><label>{uiText("收件邮箱")}<input type="email" required value={recipient} disabled={busy} onChange={e=>setRecipient(e.target.value)} /></label><label>{uiText("应用专用密码")}<input type="password" autoComplete="new-password" value={password} disabled={busy} placeholder={view.hasSecret?uiText("已保存；留空保留"):uiText("Google 提供的 16 位密码")} onChange={e=>setPassword(e.target.value)} /></label><p>{uiText("请先在 Google 账号开启两步验证并生成应用专用密码。密码保存于 Windows 凭据保险库，不写入通知记录。")}</p><a href="https://myaccount.google.com/apppasswords" target="_blank" rel="noreferrer">{uiText("打开 Google 应用专用密码设置")}</a><div className="v3-notification-actions"><button type="submit" disabled={busy}>{uiText("保存邮件设置")}</button></div></form><div className="v3-notification-actions"><button disabled={busy||!view.hasSecret} onClick={()=>void act(async()=>{await api.command({action:"TEST",channel:"EMAIL"});return uiText("Gmail 已接收测试邮件，请检查收件箱（含垃圾邮件）。");})}>{uiText("发送测试邮件")}</button><button disabled={busy||!view.hasSecret} onClick={()=>void act(async()=>{await api.command({action:"CHANNEL",channel:"EMAIL",enabled:!channel("EMAIL")});return channel("EMAIL")?uiText("邮件提醒已关闭。"):uiText("邮件提醒已开启。");})}>{channel("EMAIL")?uiText("关闭邮件提醒"):uiText("开启邮件提醒")}</button><button disabled={busy||!view.hasSecret} onClick={()=>void act(async()=>{await api.command({action:"FORGET_PASSWORD"});return uiText("已移除保存的密码，并关闭邮件提醒。");})}>{uiText("移除保存的密码")}</button></div><p>{uiText("Dot 需要另行建立 Gmail 新邮件触发规则，筛选发件账号及 [AIWR_EVENT]。邮件到达、Dot 触发和它读取 Router 原文是三个独立步骤。")}</p></details></>}
 {view&&<details><summary>{uiText("最近发送记录 ·")} {tc("{0} 条记录",view.history.length)}</summary><p>{uiText("「发送通道已接收」不代表你已看到通知。结果不确定时不自动重发；临时拒绝最多尝试三次。")}</p>{view.history.length===0?<p>{uiText("暂无发送记录。")}</p>:view.history.map(r=><p key={`${r.eventSequence}-${r.channel}`}>{uiText("通知 #")}{r.eventSequence} · {uiText(channels[r.channel])} · {r.status==="FAILED"&&r.attempts>=3?uiText("发送失败，已停止重试"):statuses[r.status]??r.status} · {tc("{0} 次尝试",r.attempts)}{r.errorCode&&` · ${errors[r.errorCode]??r.errorCode}`}</p>)}</details>}
 </section>;
}
