import { useEffect, useState } from "react";
import { disableWebPush, enableWebPush, pushSetupState, type PushSetupState } from "../../mobile/push";

export type DeliveryView = { account:string; recipient:string; hasSecret:boolean; windowsStatus:string; channels:{channel:string;enabled:boolean}[]; history:{eventSequence:number;channel:string;status:string;attempts:number;errorCode:string|null;updatedAt:number}[] };
export type DeliveryApi = { desktop:boolean; settings():Promise<DeliveryView>; command(input:unknown):Promise<string> };
const channels:Record<string,string>={WEB:"浏览器",WINDOWS:"Windows",EMAIL:"邮件"};
const statuses:Record<string,string>={PENDING:"等待发送",SENDING:"正在发送",SENT:"发送通道已接收",FAILED:"发送失败，等待有限重试",UNKNOWN:"发送结果不确定，请先核对",SKIPPED:"未发送"};
const pushStates:Record<PushSetupState,string>={UNSUPPORTED:"此浏览器不支持推送",NOT_REQUESTED:"尚未允许通知",DENIED:"浏览器已拒绝权限，请到站点设置允许",SUPPORTED_NOT_SUBSCRIBED:"尚未订阅",UPDATING:"通知组件正在更新",SUBSCRIBED:"此浏览器已订阅"};
const errors:Record<string,string>={EMAIL_APP_PASSWORD_REQUIRED:"请先在桌面工具保存 Gmail 应用专用密码。",EMAIL_APP_PASSWORD_FORMAT_INVALID:"请填写 Google 提供的 16 位应用专用密码。",EMAIL_ADDRESS_INVALID:"邮箱地址格式不正确。",SMTP_REJECTED_CHECK_ACCOUNT:"Gmail 拒绝发信，请检查账号及应用专用密码。",SMTP_ACCEPTANCE_UNKNOWN:"邮件发送结果不确定。请先检查收件箱，避免重复发送。",WEB_PUSH_NO_SUBSCRIPTION:"尚无浏览器订阅，请先在网页通知入口开启推送。",WINDOWS_NOTIFICATIONS_DISABLED:"Windows 未允许此工具显示通知，请在系统通知设置中开启。",NOTIFICATION_WEB_URL_UNAVAILABLE:"尚未配置可访问的通知网页地址。"};
export function NotificationDeliveryPanel({api}:{api:DeliveryApi}){
 const [view,setView]=useState<DeliveryView|null>(null),[account,setAccount]=useState(""),[recipient,setRecipient]=useState(""),[password,setPassword]=useState(""),[push,setPush]=useState<PushSetupState|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{let active=true;void api.settings().then(v=>{if(active){setView(v);setAccount(v.account);setRecipient(v.recipient);}}).catch(e=>{if(active)setError(String(e));});if(!api.desktop)void pushSetupState().then(s=>{if(active)setPush(s);}).catch(()=>{if(active)setPush("UNSUPPORTED");});const timer=setInterval(()=>{void api.settings().then(v=>{if(active)setView(v);}).catch(()=>{});},5000);return()=>{active=false;clearInterval(timer);};},[api]);
 async function act(work:()=>Promise<string>){if(busy)return;setBusy(true);setMessage("");setError("");try{setMessage(await work());setView(await api.settings());}catch(e){const raw=String(e).replace(/^Error: /,"");setError(errors[raw]??raw);}finally{setBusy(false);}}
 function channel(name:string){return view?.channels.find(c=>c.channel===name)?.enabled??false;}
 return <section aria-label="提醒推送" className="v3-notification-delivery"><h2>提醒推送</h2><p>新结果和明确失败会提醒；普通进度保留在通知列表。开启后从当前时间开始，不补发旧记录。</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {api.desktop?<p>浏览器通知：在「网页通知入口」打开的浏览器里开启。{channel("WEB")?" Router 已启用浏览器发送通道。":""}</p>:<div><h3>浏览器通知</h3><p>{push?pushStates[push]:"正在检查权限…"}</p><div className="v3-notification-actions"><button disabled={busy||push==="UNSUPPORTED"||push==="DENIED"} onClick={()=>void act(async()=>{await enableWebPush();await api.command({action:"CHANNEL",channel:"WEB",enabled:true});setPush(await pushSetupState());return "浏览器推送已开启。";})}>开启此浏览器推送</button><button disabled={busy||push!=="SUBSCRIBED"} onClick={()=>void act(async()=>{await disableWebPush();setPush(await pushSetupState());return "已关闭此浏览器的订阅。";})}>关闭此浏览器推送</button><button disabled={busy||push!=="SUBSCRIBED"} onClick={()=>void act(async()=>{await api.command({action:"TEST",channel:"WEB"});return "推送服务已接收测试通知，请检查浏览器或系统通知。";})}>测试浏览器通知</button></div></div>}
 {api.desktop&&view&&<><div><h3>Windows 桌面通知</h3><p>{view.windowsStatus==="ENABLED"?"Windows 允许此工具通知。":view.windowsStatus==="NOT_INITIALIZED"?"首次使用，请先发送测试通知，然后开启提醒。":"Windows 通知不可用或被系统设置禁用。"} 点击通知会打开对应的 Router 通知。</p><div className="v3-notification-actions"><button disabled={busy||view.windowsStatus!=="ENABLED"} onClick={()=>void act(async()=>{await api.command({action:"CHANNEL",channel:"WINDOWS",enabled:!channel("WINDOWS")});return channel("WINDOWS")?"Windows 提醒已关闭。":"Windows 提醒已开启。";})}>{channel("WINDOWS")?"关闭 Windows 提醒":"开启 Windows 提醒"}</button><button disabled={busy||!["ENABLED","NOT_INITIALIZED"].includes(view.windowsStatus)} onClick={()=>void act(async()=>{await api.command({action:"TEST",channel:"WINDOWS"});return "已提交 Windows 测试通知。横幅是否显示由系统通知设置决定。";})}>测试 Windows 通知</button></div></div>
 <details><summary>Gmail 邮件提醒 · {channel("EMAIL")?"已开启":"未开启"}</summary><p>固定使用 smtp.gmail.com:465，TLS 加密。主题前缀 [AIWR_EVENT]；邮件包含来源和原文链接，方便 Dot 的新邮件触发规则读取。</p><form onSubmit={e=>{e.preventDefault();void act(async()=>{await api.command({action:"EMAIL",account,recipient,password:password||null});setPassword("");return "邮件设置已保存。请先发送测试邮件，再开启提醒。";});}}><label>发信 Gmail 账号<input type="email" required value={account} disabled={busy} onChange={e=>setAccount(e.target.value)} /></label><label>收件邮箱<input type="email" required value={recipient} disabled={busy} onChange={e=>setRecipient(e.target.value)} /></label><label>应用专用密码<input type="password" autoComplete="new-password" value={password} disabled={busy} placeholder={view.hasSecret?"已保存；留空保留":"Google 提供的 16 位密码"} onChange={e=>setPassword(e.target.value)} /></label><p>请先在 Google 账号开启两步验证并生成应用专用密码。密码保存于 Windows 凭据保险库，不写入通知记录。</p><a href="https://myaccount.google.com/apppasswords" target="_blank" rel="noreferrer">打开 Google 应用专用密码设置</a><div className="v3-notification-actions"><button type="submit" disabled={busy}>保存邮件设置</button></div></form><div className="v3-notification-actions"><button disabled={busy||!view.hasSecret} onClick={()=>void act(async()=>{await api.command({action:"TEST",channel:"EMAIL"});return "Gmail 已接收测试邮件，请检查收件箱（含垃圾邮件）。";})}>发送测试邮件</button><button disabled={busy||!view.hasSecret} onClick={()=>void act(async()=>{await api.command({action:"CHANNEL",channel:"EMAIL",enabled:!channel("EMAIL")});return channel("EMAIL")?"邮件提醒已关闭。":"邮件提醒已开启。";})}>{channel("EMAIL")?"关闭邮件提醒":"开启邮件提醒"}</button><button disabled={busy||!view.hasSecret} onClick={()=>void act(async()=>{await api.command({action:"FORGET_PASSWORD"});return "已移除保存的密码，并关闭邮件提醒。";})}>移除保存的密码</button></div><p>Dot 需要另行建立 Gmail 新邮件触发规则，筛选发件账号及 [AIWR_EVENT]。邮件到达、Dot 触发和它读取 Router 原文是三个独立步骤。</p></details></>}
 {view&&<details><summary>最近发送记录 · {view.history.length} 条</summary><p>「发送通道已接收」不代表你已看到通知。结果不确定时不自动重发；临时拒绝最多尝试三次。</p>{view.history.length===0?<p>暂无发送记录。</p>:view.history.map(r=><p key={`${r.eventSequence}-${r.channel}`}>通知 #{r.eventSequence} · {channels[r.channel]} · {r.status==="FAILED"&&r.attempts>=3?"发送失败，已停止重试":statuses[r.status]??r.status} · {r.attempts} 次{r.errorCode&&` · ${errors[r.errorCode]??r.errorCode}`}</p>)}</details>}
 </section>;
}
