import {t as uiText,useLanguage} from "../../i18n";
import {useEffect,useRef,useState} from "react";
import {LoaderCircle,Check,AlertCircle} from "lucide-react";
import {invoke} from "@tauri-apps/api/core";
export type SharedCodexStatus={enabled:boolean;ready:boolean;desktopConnected:boolean;state:string;updatePending?:boolean;launchProgress?:{step:string;state:string;errorCode?:string|null;updatedAt:number}|null};
export type SharedCodexApi={status:()=>Promise<SharedCodexStatus>;setup:()=>Promise<SharedCodexStatus>;launch?:()=>Promise<SharedCodexStatus>;disable?:()=>Promise<SharedCodexStatus>};
const nativeApi:SharedCodexApi={status:()=>invoke("shared_codex_status"),setup:()=>invoke("shared_codex_setup"),launch:()=>invoke("shared_codex_launch"),disable:()=>invoke("shared_codex_disable")};
export function SharedCodexConnection({api=nativeApi}:{api?:SharedCodexApi}){
 useLanguage();
 const[state,setState]=useState<SharedCodexStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const pending=useRef(false),revision=useRef(0),mounted=useRef(false);
 useEffect(()=>{mounted.current=true;let alive=true,lastCheck=0;const check=()=>{if(!pending.current&&lastCheck&&Date.now()-lastCheck<10000)return;lastCheck=Date.now();const current=pending.current?revision.current:++revision.current;void api.status().then(s=>{if(alive&&current===revision.current){setState(s);}}).catch(()=>{if(alive&&current===revision.current)setError(uiText("共享连接状态暂时无法读取。"));});};check();const timer=setInterval(check,1000);return()=>{alive=false;mounted.current=false;++revision.current;clearInterval(timer);};},[api]);
 async function act(action:"setup"|"status"|"launch"|"disable"){if(pending.current)return;pending.current=true;const current=++revision.current;setBusy(true);setError(null);try{const operation=api[action];if(!operation)throw Error("SHARED_ACTION_UNAVAILABLE");const value=await operation();if(mounted.current&&current===revision.current)setState(value);}catch(e){if(mounted.current&&current===revision.current){const text=String(e);setError(text.includes("SHARED_ROLLBACK_INCOMPLETE")?uiText("恢复尚未完成，请重试停用；不会启动第二个 Desktop。"):text.includes("SHARED_ROUTER_BUSY")||text.includes("SHARED_DESKTOP_BUSY")?uiText("对话正在执行，完成后再切换连接。"):text.includes("SHARED_DESKTOP_CLOSE_REQUIRED")?uiText("请先自行退出 Codex Desktop，再点这里打开。"):text.includes("SHARED_DESKTOP_PREFLIGHT_FAILED")||text.includes("SHARED_DESKTOP_CONNECTION_FAILED")?uiText("Codex 窗口未能打开，请重试。已有共享任务会保留。"):text.includes("SHARED_DESKTOP_WINDOW_UNAVAILABLE")?uiText("共享连接仍在运行，暂时无法显示窗口。请重试打开。"):text.includes("SHARED_OTHER_DESKTOP_ENDPOINT")?uiText("Desktop 已配置其他连接地址，请先核对原设置。"):text.includes("SHARED_RUNTIME_UPDATE_PENDING")?uiText("旧共享后端仍在使用，请先停用再更新。"):text.includes("SHARED_DESKTOP_BACKEND_UNRESOLVED")?uiText("请打开 Codex Desktop 后重试。"):uiText("共享操作未完成，请检查连接状态后重试。"));try{const next=await api.status();if(mounted.current&&current===revision.current)setState(next);}catch{}}}finally{++revision.current;pending.current=false;if(mounted.current)setBusy(false);}}
 const prepared=state?.state==="SHARED_PREPARED"||(state?.enabled&&state.ready&&!state.desktopConnected);
 const title=state?.desktopConnected&&state.enabled?uiText("Desktop 已接入共享连接"):state?.ready?uiText("共享连接已准备好"):state?.enabled?uiText("正在恢复共享连接"):uiText("Codex Desktop 共享连接");
 const progress=state?.launchProgress,steps:Record<string,string>={CHECKING:uiText("检查本地连接"),LAUNCHING:uiText("启动 Codex"),CONNECTING:uiText("连接共享后端"),SHOWING:uiText("显示 Codex 窗口"),CONNECTED:uiText("共享 Codex 已打开"),FAILED:uiText("启动未完成")};
 return <section className="v4-shared-codex" aria-label={uiText("Codex Desktop 共享连接")}><h2>{uiText(title)}</h2><p>{state?.desktopConnected&&state.enabled?uiText("Router 和 Desktop 可以继续同一个对话。"):prepared?uiText("默认启动保持不变。自行退出 Desktop 后，从这里打开共享模式。"):(state?.state==="LEGACY_REPAIR_REQUIRED"||state?.state==="RECOVERY_REQUIRED")?uiText("旧连接需要恢复。先停用旧连接，再准备新版。"):state?.ready?uiText("先结束当前任务，再重启 Codex Desktop。"):state?.enabled?uiText("正在检查本地连接。已批准内容仍然保留。"):uiText("先验证本地连接；不安装证书，不提前改变 Desktop 默认启动。")}</p><button type="button" className="v3-primary" disabled={busy} onClick={()=>void act(prepared||state?.desktopConnected?"launch":state===null||state.enabled?"status":"setup")}>{busy?uiText("正在处理…"):prepared||state?.desktopConnected?uiText("打开共享 Codex"):state===null||state.enabled?uiText("检查连接"):uiText("准备共享连接")}</button>{api.disable&&(state?.enabled||state?.ready||(state?.state==="LEGACY_REPAIR_REQUIRED"||state?.state==="RECOVERY_REQUIRED"))&&<button type="button" disabled={busy} onClick={()=>void act("disable")}>{uiText("停用共享连接")}</button>}{state?.updatePending&&<p role="status">{uiText("共享后端有更新；停用后重新准备即可。")}</p>}{progress&&(busy||progress.state==="FAILED"&&!state?.desktopConnected)&&<div className="v4-shared-progress" role="status" aria-live="polite">{progress.state==="FAILED"?<AlertCircle size={16}/>:progress.state==="DONE"?<Check size={16}/>:<LoaderCircle size={16} className="v4-progress-spinner"/>}<span>{steps[progress.step]??uiText("正在处理…")}</span></div>}{error&&<p role="alert">{uiText(error)}</p>}<p className="v4-meta">{uiText("已手动转发的消息不会自动重发。")}</p></section>;
}
