import {useEffect,useRef,useState} from "react";
import {invoke} from "@tauri-apps/api/core";
export type SharedCodexStatus={enabled:boolean;ready:boolean;desktopConnected:boolean;state:string;updatePending?:boolean};
export type SharedCodexApi={status:()=>Promise<SharedCodexStatus>;setup:()=>Promise<SharedCodexStatus>;launch?:()=>Promise<SharedCodexStatus>;disable?:()=>Promise<SharedCodexStatus>};
const nativeApi:SharedCodexApi={status:()=>invoke("shared_codex_status"),setup:()=>invoke("shared_codex_setup"),launch:()=>invoke("shared_codex_launch"),disable:()=>invoke("shared_codex_disable")};
export function SharedCodexConnection({api=nativeApi}:{api?:SharedCodexApi}){
 const[state,setState]=useState<SharedCodexStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);const pending=useRef(false),revision=useRef(0),mounted=useRef(false);
 useEffect(()=>{mounted.current=true;let alive=true;const check=()=>{if(pending.current)return;const current=++revision.current;void api.status().then(s=>{if(alive&&current===revision.current){setState(s);}}).catch(()=>{if(alive&&current===revision.current)setError("共享连接状态暂时无法读取。");});};check();const timer=setInterval(check,10000);return()=>{alive=false;mounted.current=false;++revision.current;clearInterval(timer);};},[api]);
 async function act(action:"setup"|"status"|"launch"|"disable"){if(pending.current)return;pending.current=true;const current=++revision.current;setBusy(true);setError(null);try{const operation=api[action];if(!operation)throw Error("SHARED_ACTION_UNAVAILABLE");const value=await operation();if(mounted.current&&current===revision.current)setState(value);}catch(e){if(mounted.current&&current===revision.current){const text=String(e);setError(text.includes("SHARED_ROLLBACK_INCOMPLETE")?"恢复尚未完成，请重试停用；不会启动第二个 Desktop。":text.includes("SHARED_ROUTER_BUSY")||text.includes("SHARED_DESKTOP_BUSY")?"对话正在执行，完成后再切换连接。":text.includes("SHARED_DESKTOP_CLOSE_REQUIRED")?"请先自行退出 Codex Desktop，再点这里打开。":text.includes("SHARED_DESKTOP_PREFLIGHT_FAILED")||text.includes("SHARED_DESKTOP_CONNECTION_FAILED")?"Codex 未能保持运行或显示窗口，共享启用已撤回。":text.includes("SHARED_OTHER_DESKTOP_ENDPOINT")?"Desktop 已配置其他连接地址，请先核对原设置。":text.includes("SHARED_RUNTIME_UPDATE_PENDING")?"旧共享后端仍在使用，请先停用再更新。":text.includes("SHARED_DESKTOP_BACKEND_UNRESOLVED")?"请打开 Codex Desktop 后重试。":"共享操作未完成，请检查连接状态后重试。");try{const next=await api.status();if(mounted.current&&current===revision.current)setState(next);}catch{}}}finally{pending.current=false;if(mounted.current)setBusy(false);}}
 const prepared=state?.state==="SHARED_PREPARED"||(state?.enabled&&state.ready&&!state.desktopConnected);
 const title=state?.desktopConnected&&state.enabled?"Desktop 已接入共享连接":state?.ready?"共享连接已准备好":state?.enabled?"正在恢复共享连接":"Codex Desktop 共享连接";
 return <section className="v4-shared-codex" aria-label="Codex Desktop 共享连接"><h2>{title}</h2><p>{state?.desktopConnected&&state.enabled?"Router 和 Desktop 可以继续同一个对话。":prepared?"默认启动保持不变。自行退出 Desktop 后，从这里打开共享模式。":(state?.state==="LEGACY_REPAIR_REQUIRED"||state?.state==="RECOVERY_REQUIRED")?"旧连接需要恢复。先停用旧连接，再准备新版。":state?.ready?"先结束当前任务，再重启 Codex Desktop。":state?.enabled?"正在检查本地连接。已批准内容仍然保留。":"先验证本地连接；不安装证书，不提前改变 Desktop 默认启动。"}</p><button type="button" className="v3-primary" disabled={busy} onClick={()=>void act(prepared?"launch":state===null||state.enabled?"status":"setup")}>{busy?"正在处理…":prepared?"打开共享 Codex":state===null||state.enabled?"检查连接":"准备共享连接"}</button>{api.disable&&(state?.enabled||state?.ready||(state?.state==="LEGACY_REPAIR_REQUIRED"||state?.state==="RECOVERY_REQUIRED"))&&<button type="button" disabled={busy} onClick={()=>void act("disable")}>停用共享连接</button>}{state?.updatePending&&<p role="status">共享后端有更新；停用后重新准备即可。</p>}{error&&<p role="alert">{error}</p>}<p className="v4-meta">已手动转发的消息不会自动重发。</p></section>;
}
