import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {SwipeDeleteRow} from './SwipeDeleteRow';
afterEach(cleanup);
function setup(){const remove=vi.fn(),open=vi.fn();const view=render(<SwipeDeleteRow label="exact" onDelete={remove}><button onClick={open}>进入</button></SwipeDeleteRow>);return {remove,open,row:view.container.firstElementChild as HTMLElement};}
function touch(row:HTMLElement,dx:number,dy=0){fireEvent.touchStart(row,{touches:[{clientX:140,clientY:140}]});const move=new Event('touchmove',{bubbles:true,cancelable:true});Object.defineProperty(move,'touches',{value:[{clientX:140+dx,clientY:140+dy}]});fireEvent(row,move);fireEvent.touchEnd(row,{touches:[]});return move;}
it.each([[-90,'right'],[90,'left']])('accepts native touch movement %i, then deletes once on its revealed side',(dx,side)=>{const {row,remove,open}=setup();const move=touch(row,dx as number);expect(move.defaultPrevented).toBe(true);expect(row.dataset.open).toBe('true');expect(row.dataset.side).toBe(side);fireEvent.click(screen.getByRole('button',{name:'进入'}));expect(open).not.toHaveBeenCalled();fireEvent.click(screen.getAllByRole('button',{name:'删除 exact'})[0]);expect(remove).toHaveBeenCalledTimes(1);});
it('keeps a vertical native touch scroll uncancelled and the action inaccessible',()=>{const {row}=setup();const move=touch(row,4,95);expect(move.defaultPrevented).toBe(false);expect(row.dataset.open).toBe('false');expect(row.dataset.revealed).toBe('false');expect(row.querySelector('.agbrio-swipe-delete')).toHaveAttribute('aria-hidden','true');});
it('touch cancellation and a second finger close the action without deletion',()=>{const {row,remove}=setup();touch(row,90);fireEvent.touchStart(row,{touches:[{clientX:140,clientY:140},{clientX:160,clientY:140}]});expect(row.dataset.revealed).toBe('false');touch(row,-90);fireEvent.touchCancel(row);expect(row.dataset.revealed).toBe('false');expect(remove).not.toHaveBeenCalled();});
it('preserves screen-edge Back and closes another open row',()=>{const {row}=setup();fireEvent.touchStart(row,{touches:[{clientX:5,clientY:140}]});fireEvent.touchMove(row,{touches:[{clientX:95,clientY:140}]});fireEvent.touchEnd(row);expect(row.dataset.open).toBe('false');touch(row,90);fireEvent(window,new CustomEvent('agbrio-swipe-open',{detail:'another-exact-row'}));expect(row.dataset.revealed).toBe('false');});
