//! Owner-local native gateway with explicit prepare/activate/disable transactions.
//! Preparing never changes Desktop's persistent endpoint or certificate trust.
use serde::{Serialize,Deserialize};
use std::{path::{Path,PathBuf},sync::{Mutex,OnceLock},process::Command,fs};
use sha2::{Digest,Sha256};
#[derive(Clone)]struct Assets{source:PathBuf,node:PathBuf}
static ASSETS:OnceLock<Assets>=OnceLock::new();static START:Mutex<()>=Mutex::new(());
#[derive(Clone,Serialize,Deserialize)]#[serde(rename_all="camelCase")]
struct Settings{enabled:bool,#[serde(default)]format:u32,#[serde(default)]phase:String,binary:PathBuf,version:String,owner_sid:String,port:u16,instance:String,#[serde(default)]desktop:Option<PathBuf>}
#[derive(Serialize,Deserialize)]#[serde(rename_all="camelCase")]
pub(crate)struct Status{pub enabled:bool,pub ready:bool,pub desktop_connected:bool,pub state:String,pub update_pending:bool}
fn folder()->Result<PathBuf,String>{Ok(PathBuf::from(std::env::var_os("LOCALAPPDATA").ok_or("SHARED_LOCAL_DATA_UNAVAILABLE")?).join("AIWorkRouter/codex-shared"))}
fn settings()->Result<Option<Settings>,String>{let p=folder()?.join("settings.json");if !p.exists(){return Ok(None)}serde_json::from_slice(&fs::read(p).map_err(|_|"SHARED_SETTINGS_UNAVAILABLE")?).map(Some).map_err(|_|"SHARED_SETTINGS_INVALID".into())}
fn tool_path(path:PathBuf)->PathBuf{
 #[cfg(windows)]{let text=path.to_string_lossy();if let Some(drive)=text.strip_prefix(r"\\?\"){if drive.as_bytes().get(1)==Some(&b':'){return PathBuf::from(drive)}}}
 path
}
pub(crate)fn configure(source:PathBuf,node:PathBuf){let _=ASSETS.set(Assets{source:tool_path(source),node:tool_path(node)});}
#[cfg(windows)]fn hidden(c:&mut Command){use std::os::windows::process::CommandExt;c.creation_flags(0x08000000);}
#[cfg(not(windows))]fn hidden(_: &mut Command){}
fn health(s:&Settings)->Option<serde_json::Value>{if s.format!=2{return None}let client=reqwest::blocking::Client::builder().no_proxy().timeout(std::time::Duration::from_secs(2)).build().ok()?;let v=client.get(format!("http://127.0.0.1:{}/health",s.port)).send().ok()?.json::<serde_json::Value>().ok()?;(v["instance"].as_str()==Some(&s.instance)).then_some(v)}
pub(crate)fn status()->Status{
 let fallback=Status{enabled:false,ready:false,desktop_connected:false,state:"INDEPENDENT".into(),update_pending:false};
 let Ok(Some(s))=settings()else{return fallback};if s.phase=="RECOVERY_REQUIRED"{return Status{state:"RECOVERY_REQUIRED".into(),..fallback}}if s.format!=2{return Status{state:if s.enabled{"LEGACY_REPAIR_REQUIRED"}else{"INDEPENDENT"}.into(),..fallback}};
 let h=health(&s);let ready=h.as_ref().is_some_and(|h|h["ready"]==true);let desktop=h.as_ref().is_some_and(|h|h["desktopConnected"]==true);
 Status{enabled:s.enabled,ready,desktop_connected:desktop,state:if s.phase=="RECOVERY_REQUIRED"{"RECOVERY_REQUIRED"}else if s.phase=="PREPARED"&&ready{"SHARED_PREPARED"}else if s.enabled&&desktop{"SHARED_CONNECTED"}else if s.enabled{"SHARED_RECONNECTING"}else{"INDEPENDENT"}.into(),update_pending:runtime_update_pending()}
}
fn copy_tree(from:&Path,to:&Path)->Result<(),String>{fs::create_dir_all(to).map_err(|_|"SHARED_RUNTIME_COPY_FAILED")?;for e in fs::read_dir(from).map_err(|_|"SHARED_RUNTIME_COPY_FAILED")?{let e=e.map_err(|_|"SHARED_RUNTIME_COPY_FAILED")?;let ty=e.file_type().map_err(|_|"SHARED_RUNTIME_COPY_FAILED")?;if ty.is_symlink(){return Err("SHARED_RUNTIME_LINK_REJECTED".into())}if ty.is_dir(){copy_tree(&e.path(),&to.join(e.file_name()))?}else{fs::copy(e.path(),to.join(e.file_name())).map_err(|_|"SHARED_RUNTIME_COPY_FAILED")?;}}Ok(())}
fn asset_stamp(a:&Assets)->Result<String,String>{let mut digest=Sha256::new();for name in ["runtime.mjs","transport.mjs","peer-owner.ps1","desktop-runtime.ps1","peer-service.ps1","control.mjs","environment.ps1","desktop-identity.ps1"]{digest.update(fs::read(a.source.join(name)).map_err(|_|"SHARED_RUNTIME_ASSET_MISSING")?);}digest.update(fs::read(&a.node).map_err(|_|"SHARED_NODE_MISSING")?);let ws=a.source.parent().ok_or("SHARED_RUNTIME_ASSET_MISSING")?.join("browser-executor/node_modules/ws");for name in ["index.js","package.json"]{digest.update(fs::read(ws.join(name)).map_err(|_|"SHARED_WS_MISSING")?);}let mut files:Vec<_>=fs::read_dir(ws.join("lib")).map_err(|_|"SHARED_WS_MISSING")?.filter_map(Result::ok).collect();files.sort_by_key(|f|f.file_name());for f in files{digest.update(fs::read(f.path()).map_err(|_|"SHARED_WS_MISSING")?);}Ok(format!("{:x}",digest.finalize()))}
fn runtime_update_pending()->bool{let Some(a)=ASSETS.get()else{return false};let Ok(stamp)=asset_stamp(a)else{return true};folder().ok().and_then(|f|fs::read_to_string(f.join("runtime/version")).ok()).is_some_and(|v|v!=stamp)}
fn same_supervisor_identity(saved:&serde_json::Value,current:&serde_json::Value,expected_image:&str,expected_owner:&str)->bool{
 let normalized=|p:&str|p.replace('/',"\\").trim_start_matches("\\\\?\\").to_ascii_lowercase();
 saved["pid"].as_u64().is_some_and(|id|id>0&&current["pid"].as_u64()==Some(id))&&saved["createdAt"].as_str().is_some_and(|v|!v.is_empty()&&current["createdAt"].as_str()==Some(v))&&current["ownerSid"].as_str()==Some(expected_owner)&&saved["ownerSid"].as_str()==Some(expected_owner)&&current["imagePath"].as_str().is_some_and(|p|normalized(p)==normalized(expected_image))&&saved["imagePath"].as_str().is_some_and(|p|normalized(p)==normalized(expected_image))
}
#[cfg(windows)]fn supervisor_alive()->bool{
 let Ok(folder)=folder()else{return false;};let Some(s)=settings().ok().flatten()else{return false;};let Some(saved)=fs::read(folder.join("ready.json")).ok().and_then(|b|serde_json::from_slice::<serde_json::Value>(&b).ok()).and_then(|v|v.get("supervisorIdentity").cloned())else{return false;};let Some(pid)=saved["pid"].as_u64().filter(|p|*p>0&&*p<=u32::MAX as u64)else{return false;};
 let mut query=Command::new(PathBuf::from(std::env::var_os("WINDIR").unwrap_or_default()).join("System32/WindowsPowerShell/v1.0/powershell.exe"));query.args(["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File"]).arg(folder.join("runtime/peer-service.ps1")).arg("-QueryPid").arg(pid.to_string());hidden(&mut query);
 let Some(current)=query.output().ok().filter(|v|v.status.success()).and_then(|v|serde_json::from_slice::<serde_json::Value>(&v.stdout).ok())else{return false;};same_supervisor_identity(&saved,&current,&folder.join("runtime/node.exe").to_string_lossy(),&s.owner_sid)
}
#[cfg(not(windows))]fn supervisor_alive()->bool{false}

fn pin(a:&Assets)->Result<PathBuf,String>{let root=folder()?.join("runtime");let stamp=asset_stamp(a)?;if fs::read_to_string(root.join("version")).ok().as_deref()==Some(&stamp){return Ok(root)}if supervisor_alive(){return Err("SHARED_RUNTIME_UPDATE_PENDING".into())}let staged=folder()?.join(format!("runtime-next-{}",uuid::Uuid::new_v4()));copy_tree(&a.source,&staged)?;copy_tree(&a.source.parent().ok_or("SHARED_RUNTIME_ASSET_MISSING")?.join("browser-executor/node_modules/ws"),&staged.join("ws"))?;fs::copy(&a.node,staged.join("node.exe")).map_err(|_|"SHARED_NODE_COPY_FAILED")?;fs::write(staged.join("version"),stamp).map_err(|_|"SHARED_RUNTIME_COPY_FAILED")?;let previous=folder()?.join(format!("runtime-previous-{}",uuid::Uuid::new_v4()));let had=root.exists();if had{fs::rename(&root,&previous).map_err(|_|"SHARED_RUNTIME_UPDATE_PENDING")?}if fs::rename(&staged,&root).is_err(){if had{let _=fs::rename(previous,&root);}return Err("SHARED_RUNTIME_COPY_FAILED".into())}Ok(root)}
fn control(action:&str,binary:Option<&Path>,version:Option<&str>,desktop:Option<&Path>)->Result<Status,String>{let a=ASSETS.get().ok_or("SHARED_RUNTIME_NOT_CONFIGURED")?;fs::create_dir_all(folder()?).map_err(|_|"SHARED_SETTINGS_UNAVAILABLE")?;let input=folder()?.join("control-request.json");let value=serde_json::json!({"action":action,"directory":folder()?,"scripts":a.source,"binary":binary,"version":version,"desktop":desktop});fs::write(&input,serde_json::to_vec(&value).unwrap()).map_err(|_|"SHARED_SETTINGS_UNAVAILABLE")?;let mut command=Command::new(&a.node);command.arg(a.source.join("control.mjs")).arg(input);hidden(&mut command);let output=command.output().map_err(|_|"SHARED_LIFECYCLE_FAILED")?;if !output.status.success(){let error=String::from_utf8_lossy(&output.stderr).trim().to_string();return Err(if error.starts_with("SHARED_")&&error.len()<128{error}else{"SHARED_LIFECYCLE_FAILED".into()})}serde_json::from_slice(&output.stdout).map_err(|_|"SHARED_LIFECYCLE_FAILED".into())}
pub(crate)fn enabled()->bool{settings().ok().flatten().is_some_and(|s|s.enabled&&s.format==2&&s.phase=="ACTIVE")}
pub(crate)fn transport_command()->Result<Option<Command>,String>{let Some(s)=settings()?else{return Ok(None)};if s.format!=2&&s.enabled{return Err("SHARED_LEGACY_REPAIR_REQUIRED".into())}if s.phase=="RECOVERY_REQUIRED"{return Err("SHARED_ROLLBACK_INCOMPLETE".into())}if !s.enabled{return Ok(None)}if s.phase!="ACTIVE"||!health(&s).is_some_and(|h|h["ready"]==true){return Err("SHARED_RECONNECTING".into())}let root=folder()?.join("runtime");let mut command=Command::new(root.join("node.exe"));command.arg(root.join("transport.mjs")).arg(format!("ws://127.0.0.1:{}/rpc",s.port));hidden(&mut command);Ok(Some(command))}
pub(crate)fn disable()->Result<Status,String>{let _lock=START.lock().map_err(|_|"SHARED_START_UNAVAILABLE")?;control("disable",None,None,None)}
pub(crate)fn launch()->Result<Status,String>{let _lock=START.lock().map_err(|_|"SHARED_START_UNAVAILABLE")?;control("launch",None,None,None)}
#[cfg(windows)]pub(crate)fn setup()->Result<Status,String>{let _lock=START.lock().map_err(|_|"SHARED_START_UNAVAILABLE")?;let a=ASSETS.get().ok_or("SHARED_RUNTIME_NOT_CONFIGURED")?;if let Some(s)=settings()?{if s.format==2&&!runtime_update_pending()&&health(&s).is_some_and(|h|h["ready"]==true){return Ok(status())}control("disable",None,None,None)?;}
 let mut discovery=Command::new(PathBuf::from(std::env::var_os("WINDIR").ok_or("SHARED_OWNER_UNAVAILABLE")?).join("System32/WindowsPowerShell/v1.0/powershell.exe"));discovery.args(["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File"]).arg(a.source.join("desktop-runtime.ps1"));hidden(&mut discovery);let output=discovery.output().map_err(|_|"SHARED_DESKTOP_BACKEND_UNRESOLVED")?;if !output.status.success(){return Err("SHARED_DESKTOP_BACKEND_UNRESOLVED".into())}let v:serde_json::Value=serde_json::from_slice(&output.stdout).map_err(|_|"SHARED_DESKTOP_BACKEND_UNRESOLVED")?;let binary=PathBuf::from(v["binary"].as_str().ok_or("SHARED_NATIVE_BINARY_UNVERIFIED")?);let version=v["version"].as_str().ok_or("SHARED_NATIVE_BINARY_UNVERIFIED")?;let desktop=PathBuf::from(v["desktop"].as_str().ok_or("SHARED_DESKTOP_BINARY_UNRESOLVED")?);pin(a)?;control("setup",Some(&binary),Some(version),Some(&desktop))}
#[cfg(not(windows))]pub(crate)fn setup()->Result<Status,String>{Err("SHARED_WINDOWS_REQUIRED".into())}
#[cfg(test)]mod tests{use super::*;
#[cfg(windows)]#[test]fn native_tool_paths_remove_only_local_drive_extended_prefix(){assert_eq!(tool_path(PathBuf::from(r"\\?\D:\apps\AI Work Router\node.exe")),PathBuf::from(r"D:\apps\AI Work Router\node.exe"));assert_eq!(tool_path(PathBuf::from(r"\\?\UNC\server\share")),PathBuf::from(r"\\?\UNC\server\share"));}#[test]fn recycled_pid_wrong_owner_and_wrong_image_never_match_supervisor(){let saved=serde_json::json!({"pid":42,"createdAt":"134056789123456789","ownerSid":"S-1-5-21-fixture","imagePath":"C:/fixture/node.exe"});assert!(same_supervisor_identity(&saved,&saved,"C:\\fixture\\node.exe","S-1-5-21-fixture"));for(field,value)in[("pid",serde_json::json!(43)),("createdAt",serde_json::json!("134056789123456790")),("ownerSid",serde_json::json!("S-1-other")),("imagePath",serde_json::json!("C:/another/node.exe"))]{let mut current=saved.clone();current[field]=value;assert!(!same_supervisor_identity(&saved,&current,"C:/fixture/node.exe","S-1-5-21-fixture"));}assert!(!same_supervisor_identity(&saved,&serde_json::Value::Null,"C:/fixture/node.exe","S-1-5-21-fixture"));}}
